### PR TITLE
refactor dart manifest

### PR DESCRIPTION
**Pull request by guillermooo**
Can't get this to work via

```
scoop install .\dart.json
```

Please take a look if you can.

### CODE REVIEW

**Comment by guillermooo** [comment]
```
bucket refactor-dart-manifest* $ ConvertFrom-Json -InputObject ([string](gc .\dart.json)) | fl *


version      : 1.10.0
license      : BSD
homepage     : https://www.dartlang.org/
extract_dir  : dart-sdk
bin          : {bin\dart.exe, bin\dart2js.bat, bin\dartanalyzer.bat, bin\dartdocgen.bat...}
env_add_path : {bin, %APPDATA%\Pub\Cache\bin}
architecture : @{64bit=; 32bit=}
checkver     : @{url=http://storage.googleapis.com/dart-archive/channels/stable/release/latest/VERSION;
               re=\s*"version"\s*:\s*(\d+\.\d+\.\d+(?:.+)?)}
notes        : Dart sdk installed.



bucket refactor-dart-manifest* $ scoop install https://github.com/guillermooo-forks/scoop/blob/refactor-dart-manifest/bucket/dart.json
convertfrom-json : Invalid JSON primitive: .
At C:\Users\Guillermo\appdata\local\scoop\apps\scoop\current\lib\manifest.ps1:20 char:9
+     $str | convertfrom-json
+            ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand

couldn't find manifest for https://github.com/guillermooo-forks/scoop/blob/refactor-dart-manifest/bucket/dart.json
```

**Comment by guillermooo** [comment]
Note that the error is more cryptic if installing from the local machine:

```
bucket refactor-dart-manifest* $ scoop install .\dart.json
error: An exception occurred during a WebClient request.
couldn't find manifest for .\dart.json
```

**Comment by lukesampson** [comment]
`https://github.com/guillermooo-forks/scoop/blob/refactor-dart-manifest/bucket/dart.json` is an HTML page, you would need to use the "raw" version at `https://raw.githubusercontent.com/guillermooo-forks/scoop/refactor-dart-manifest/bucket/dart.json` for the install to work.

For the local machine error, it looks like it really just can't find the file—do you need to use `scoop install bucket/dart` instead?

**Comment by guillermooo** [comment]
Using the raw page works. Should have realized that...

I'm in the bucket dir, and `dir dart.json` works. Not sure what might be tripping `scoop` or myself up.

Just noticed that the `%APPDATA%\\...` path that should be added to `$PATH` isn't working. Any workarounds? The post-install script maybe?

**Comment by guillermooo** [comment]
Oddly, this works, though:

```
 gi .\dart.json | %{ scoop install $_.fullname }
```

**Comment by guillermooo** [comment]
Oh, It think what might be wrong...

```
bucket refactor-dart-manifest $ gi .\dart.json | %{ scoop install $_.fullname }
installing dart (1.10.0)
loading https://storage.googleapis.com/dart-archive/channels/stable/release/latest/sdk/dartsdk-windows-x64-release.zip from cache...
checking hash...ok
extracting...done
creating shim for dart
creating shim for dart2js
creating shim for dartanalyzer
creating shim for dartdocgen
creating shim for dartfmt
creating shim for docgen
creating shim for pub
dart (1.10.0) was installed successfully!
Notes
-----
Dart sdk installed.
bucket refactor-dart-manifest $ pwd

Path
----
dev:\Source\scoop\bucket
```

I'm using a custom provider.

**Comment by lukesampson** [comment]
`$env:appdata` might work instead of `%APPDATA%`.

**Comment by guillermooo** [comment]
Tried to trim the manifest. It works here. If it looks good to you, I think it's ready.

**Comment by guillermooo** [comment]
Thanks! :)

**Comment by guillermooo** [comment]
Hm. Well, appending to `$PATH` isn't working yet:

```
bucket refactor-dart-manifest* $ scoop uninstall dart
uninstalling dart (1.10.0)
removing ~\appdata\local\scoop\apps\dart\1.10.0\bin from your path
removing ~\appdata\local\scoop\apps\dart\1.10.0\$env:APPDATA\Pub\Cache\bin from your path
dart was uninstalled
```

**Comment by lukesampson** [comment]
Oh I forgot, `env_add_path` directories have to be inside the install dir. This is to encourage self-contained installs rather than ones that spread things out all over the file system.

You might have to use a `post_install` for this instead.

**Comment by guillermooo** [comment]
But then `$env:PATH` will not be cleaned up on uninstall, I suppose?

**Comment by guillermooo** [comment]
Would you consider adding a separate step in scoop to set env vars up?

**Comment by lukesampson** [comment]
That's correct, it won't be cleaned up. There is already the `env_set` step to set environment variables, like the previous dart.json used. If you can use this to place the cache directory instead the install directory rather than in %APPDATA% that's probably better.

**Comment by guillermooo** [comment]
Sorry about the spam!

I've removed the cache path. It isn't essential to get started and the pub tool informs you when it notices that isn't set up. I think that's good enough for now. I don't think the Dart SDK lets you choose a location for the pub cache.

Well, now I think this is really ready from my side!

**Comment by lukesampson** [comment]
OK sweet, thanks :+1:

**Pull request merged**
