### PR TITLE
add YARA

### PR DESCRIPTION
**Pull request by gheoan**
Could not find hash information for the binaries.

### CODE REVIEW

**Comment by r15ch13** [comment]
Currently, it's not possible to use our auto-update feature because I can't find a download URL without random strings in it ...
No idea why they don't use GitHub releases for the AppVeyor artifacts, or why they use Dropbox ... 😕

**Comment by gheoan** [comment]
@r15ch13 Thanks for the improvements! What is the reason Dropbox is used instead of AppVoyer in the manifest?

**Comment by r15ch13** [comment]
It's the latest stable version. The files from AppVeyor were build from the latest change.

**Comment by gheoan** [comment]
My understanding is that AppVeyor provides artifacts for every commit. The manifest url could be pointed at the commit which was tagged as latest version.

**Pull request merged**
