### PR TITLE
Update chromedriver to 74.0.3729.6

### PR DESCRIPTION
**Pull request by ssfjhh**
Update chromedriver to 74.0.3729.6

### CODE REVIEW

**Comment by Ash258** [comment]
Supressed by https://github.com/scoopinstaller/scoop-main/commit/e364933210bc5a3607f9a7c3000ea784e2c13b53

**Comment by ssfjhh** [comment]
Why does chromedriver appear both at scoop and scoop-main?

**Comment by Ash258** [comment]
Because main bucket will be deleted from this repo when it is sure that bucket extraction is OK for everyone.

**Comment by ssfjhh** [comment]
Thank you for your prompt reply.

**Pull request closed without merging**
