### PR TITLE
fix(autoupdate): Decode basename when extract hash

### PR DESCRIPTION
**Pull request by linsui**
Firefox, Thunderbird and uget can benefit.

### CODE REVIEW

**Comment by Ash258** [comment]
What does have basename string to do with hash extraction templates?? Do not add it into hash templates

**Comment by linsui** [comment]
substitutions will be regexEscape.

https://github.com/lukesampson/scoop/blob/79f8538b57b9021db71a279879b9032fefd1ae52/lib/autoupdate.ps1#L58

**Comment by Ash258** [comment]
Would not be more suitable to url decode it rather than specifiing all possible escapes?

`[System.Web.HttpUtility]::UrlDecode('uget-2.2.2-win32%2Bgtk3.7z')`

image

Relate ScoopInstaller/Main#471

**Comment by linsui** [comment]
Good idea! Would you pr? Then I'll close this.

**Comment by h404bi** [comment]
> Good idea! Would you pr? Then I'll close this.

Why not update your pull request?

**Comment by linsui** [comment]
I don't want to steal credit :joy: . If @Ash258 doesn't want to open another pr I'm glad to update this.

**Comment by h404bi** [comment]
> I don't want to steal credit 😂 . If @Ash258 doesn't want to open another pr I'm glad to update this.

You can commit with`Co-authored-by` like [this](https://github.com/ScoopInstaller/Main/commit/ccc24e57b6026f88d5a7b1c11150e83487a016e1)

**Comment by linsui** [comment]
Thanks! I'll have a try.

**Comment by Ash258** [comment]
I do not care for contributions. Edit this PR.

**Pull request merged**
