### PR TITLE
Update which to 2.21-2

### PR DESCRIPTION
**Pull request by rasa**

### CODE REVIEW

**Comment by rasa** [comment]
Move to msys2's build
Add autoupdate & checkver
Add 64bit build

**Comment by rasa** [comment]
This method is too complicated.

**Comment by r15ch13** [comment]
Too many deps?

**Comment by rasa** [comment]
Yeah, here's what I've found:

file:
````
msys-magic-1.dll (in file)
msys-gcc_s-1.dll (provided by gcc-libs-6.3.0-1)
msys-2.0.dll (provided by msys2-runtime-2.8.2-1)
````
grep:
````
msys-gcc_s-1.dll
msys-iconv-2.dll (provided by libiconv-1.14-2)
msys-intl-8.dll (provided by libintl-0.19.8.1-1)
msys-2.0.dll
msys-pcre-1.dll (provided by libpcre-8.40-2)
````
sed:
````
msys-gcc_s-1.dll
msys-intl-8.dll
msys-2.0.dll
````
which:
````
msys-2.0.dll
msys-gcc_s-1.dll
````

**Comment by r15ch13** [comment]
Using msys as a whole package, would be a better solution then extracting every dependency. What do you think about we remove these smaller versions and hint to the use of [msys2.json](https://github.com/lukesampson/scoop/blob/master/bucket/msys2.json)?

**Comment by rasa** [comment]
Agreed. Or host statically linked versions, per https://sourceforge.net/p/msys2/mailman/msys2-users/thread/CACac1F8WLEtNCkuCipFU%3DjNW6ZQn%2Bj-VX0y0pyGZr%3D1gUopB%3DA%40mail.gmail.com/#msg33756517

**Pull request closed without merging**
