### PR TITLE
scoop-create command to help with creating app manifests

### PR DESCRIPTION
**Pull request by deevus**
In the same vein of the Homebrew `brew create` command I was entertaining the idea of something similar for scoop. 

I wouldn't consider this complete or foolproof. Just would like to discuss the idea.

### CODE REVIEW

**Comment by lukesampson** [comment]
I like the idea. It's a nice simple initial implementation too, and I don't think it can hurt to have a guided way to put together a manifest.

**Comment by deevus** [comment]
Well there you go :)

**Comment by deevus** [comment]
In the same vein as git-* commands, what do you think of scoop being extended so that scoop-*.ps1 files on the path would be picked up as scoop commands?

**Comment by lukesampson** [comment]
I'm not sure. It might add vulnerabilities and degrade performance if the path has to be searched. Also the maintenance cost of supporting plugins like this probably isn't negligible.

Do you have a good example scenario that would make it worthwhile?

**Comment by deevus** [comment]
I don't currently have a specific example other than scoop-create but you were happy to merge that in.

**Comment by lukesampson** [comment]
OK cool.

**Comment by ntwb** [comment]
Sweet :+1:

**Pull request merged**
