### PR TITLE
Resolve linting, fix appveyor tests error

### PR DESCRIPTION
**Pull request by h404bi**

### CODE REVIEW

**Comment by rasa** [comment]
Merged this in to quiet the false positives.

**Comment by r15ch13** [comment]
Oh, forgot to run pester locally :stuck_out_tongue:

**Comment by r15ch13** [comment]
@rasa please use the "squash and merge" feature. This creates a cleaner git history. 😁

**Comment by rasa** [comment]
Will do (sorry).

**Pull request merged**
