### PR TITLE
upgrade dart stable to 1.12.1

### PR DESCRIPTION
**Pull request by devoncarew**
Upgrade dart stable to 1.12.1.

### CODE REVIEW

**Comment by devoncarew** [comment]
Hmm, sorry, I don't have enough context to diagnose this issue:

```
Installing the following packages:
pester
By installing you accept licenses for the packages.
pester not installed. An error occurred during installation:
 The remote server returned an error: (500) Internal Server Error.
The install of pester was NOT successful.
```

Perhaps re-running the appveyor build would help?

**Comment by devoncarew** [comment]
(also cc @guillermooo)

**Comment by guillermooo** [comment]
It does look like a glitch in Appveyor. Would the build re-run if you closed this PR and opened a new one from your branch?

**Comment by devoncarew** [comment]
Looks like closing and opening it did kick off a new build. Tests pass now :)

**Comment by guillermooo** [comment]
Green! @deevus @lukesampson :)

**Comment by lukesampson** [comment]
Thanks guys :+1:

**Pull request merged**
