### PR TITLE
nssm hash update 

### PR DESCRIPTION
**Pull request by deepakSP**
nssm hash update

### CODE REVIEW

**Comment by lukesampson** [comment]
The ! at the end of the hash won't work. You can test these before committing by running `scoop install /path/to/manifest.json`

**Comment by deepakSP** [comment]
@luiscoms how can i add valid hash ?

**Comment by lukesampson** [comment]
One way to get a hash is to create your manifest without hashes, install it with scoop, and copy the hashes from the warnings that scoop gives you. Hashes are numbers and letters—don't include the ! at the end of the message.

You can also `scoop install shasum` and the run `shasum path\to\download\file.zip` to get a SHA256 hash manually.

Busybox and gow (available as scoop packages) also contain a sha1sum tool.

Whichever way you choose, you should always test the install locally using `scoop install path\to\your\manifest.json` to make sure it works before submitting a pull request.

**Comment by deepakSP** [comment]
actually i tried this method but when i tried installing i got error hash miss match, so i removed it. Will try with shasum.

Thank you.

what you think about adding phar to windows executable 
example - 
if user wants to install php-cs-fixer.phar they can run
scoop install php-cs-fixer
and internally scoop will save phar file in shims directory and run
echo @php "%~dp0php-cs-fixer.phar" %* > php-cs-fixer.cmd
to create executable file.

this will save lots of time to search - how to run phar file and use inside app like phpstrom

**Comment by lukesampson** [comment]
I'm not sure about this Phar thing. It might be best to create a private [bucket](https://github.com/lukesampson/scoop/wiki/Buckets) for yourself if you want to do something like this. If it's a well-known or well-defined program that would be different, but it sounds more like a helper script.

**Comment by luiscoms** [comment]
`Phar` program is a `php` executable file

**Comment by lukesampson** [comment]
I think I roughly understand how it works.

It sounds like you're mainly interested in using the shimming capabilities of Scoop to create an .exe that calls php and passes it the .phar file, is that right?

I'd be happy to accept a pull request for something like this to [scoop-extras](https://github.com/lukesampson/scoop-extras), so the process for installing it would be something like:

```
scoop bucket add extras
scoop install php-cs-fixer
```

**Pull request merged**
