### PR TITLE
Maven: do not add directory to PATH

### PR DESCRIPTION
**Pull request by oltolm**
I have removed the `bin` directory from `%PATH%` and added `mvn.cmd` to it.

### CODE REVIEW

**Comment by brandon93s** [comment]
`mvnDebug.cmd` is often used for remote debugging. Please add it to the `bin` as well since this PR will make it unavailable.

**Comment by oltolm** [comment]
OK, I have added `mvnDebug.cmd` to `bin`.

**Comment by r15ch13** [comment]
The `env_add_path` property is used intenionally because Cygwin users can only execute `mvn` bash script which doesn't get a shim from scoop. #1237 #1415 #1544

**Comment by rasa** [comment]
If this change is still desired and viable, please open PR into ScoopInstaller/Main

**Comment by PlotCitizen** [comment]
Hi all, I have just installed maven, however a shim is not created. Can you please advise if this is per expectation?

image
image

**Comment by rashil2000** [comment]
Shims are not created because the `bin` folder is appended to the PATH

**Comment by tauinger-de** [comment]
It would help me a lot if the scoop installer would notify me about changes to the PATH. 

It would allow me to realize why e.g. the `mvn` command isn't available even after installation (-> need to re-open terminal to make PATH changes apply)

Should I open a new issue for this?

**Comment by rashil2000** [comment]
When you install a package which modifies PATH, it notifies you (for each folder that is appended to PATH).

**Comment by tauinger-de** [comment]
Sorry, but I cannot confirm that:
```
C:\Temp>scoop install maven
Installing 'maven' (3.9.6) [64bit] from main bucket
apache-maven-3.9.6-bin.zip (9,1 MB) [===============================================================================] 100%
Checking hash of apache-maven-3.9.6-bin.zip ... ok.
Extracting apache-maven-3.9.6-bin.zip ... done.
Linking ~\scoop\apps\maven\current => ~\scoop\apps\maven\3.9.6
Persisting conf
Persisting lib\ext
'maven' (3.9.6) was installed successfully!
```

**Pull request closed without merging**
