### PR TITLE
feat(core): Add pre_uninstall and post_uninstall hooks

### LINKED ISSUE #1868: pre_uninstall post_uninstall
Proposal: support pre_uninstall post_uninstall same way as pre_install post_install

### PR DESCRIPTION
**Pull request by chawyehsu**
#### Description
Introducing `pre_uninstall` and `post_uninstall` hooks.

#### Motivation and Context
Closes #1868
Closes #4218

##### hooktest1.json
```json
{
    "version": "0.2.0",
    "description": "A description",
    "homepage": "https://scoop.sh",
    "license": "UNLICENSE-or-MIT",
    "url": "https://github.com/ScoopInstaller/Scoop/archive/refs/tags/v0.2.0.tar.gz",
    "hash": "2cb9c0db892d13fed5bc49507deadc9c98f1038a96edba2d71c33a91bdb984a7",
    "extract_dir": "Scoop-0.2.0",
    "pre_uninstall": "Write-Host 'hook pre_uninstall executed.'",
    "post_uninstall": "Write-Host 'hook post_uninstall executed.'"
}
```

```
.\bin\scoop.ps1 install .\hooktest1.json
.\bin\scoop.ps1 uninstall hooktest1
```

##### hooktest2.json
```json
{
    "version": "0.2.0",
    "description": "A description",
    "homepage": "https://scoop.sh",
    "license": "UNLICENSE-or-MIT",
    "architecture": {
        "64bit": {
            "url": "https://github.com/ScoopInstaller/Scoop/archive/refs/tags/v0.2.0.tar.gz",
            "hash": "2cb9c0db892d13fed5bc49507deadc9c98f1038a96edba2d71c33a91bdb984a7",
            "extract_dir": "Scoop-0.2.0",
            "pre_uninstall": "Write-Host 'hook pre_uninstall executed.'",
            "post_uninstall": "Write-Host 'hook post_uninstall executed.'"
        }
    }
}
```

```
.\bin\scoop.ps1 install .\hooktest2.json
.\bin\scoop.ps1 uninstall hooktest2
```

#### Checklist:

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
- [x] I have ensured that I am targeting the `develop` branch.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.
- [x] I have added an entry in the CHANGELOG.

### CODE REVIEW

**Comment by rashil2000** [comment]
What's the advantage of this over `uninstaller.script`?

**Comment by niheaven** [comment]
`post_uninstall` is executed after all things done and may be needed, but does `pre_uninstall` do the same thing as `uninstall.script`?

**Comment by rashil2000** [comment]
Also, the function signature and body for `pre_install`, `post_install`, `pre_uninstall` and `post_uninstall` is exactly the same. Why not just consolidate it into a single function and pass the scripts to that function as parameter?

**Comment by chawyehsu** [comment]
Basically they have all the same functionality as the `pre/post_install` paired with `installer.script`. From my experience, `installer.script` can be used in most cases where `pre_install` is used. 

To me they make sense semantically.

> Why not just consolidate it into a single function and pass the scripts to that function as parameter?

It's ok to do such refactoring.

**Comment by rasa** [comment]
Just an FYI, [34](https://github.com/Ash258/Shovel-Ash258/search?q=pre_uninstall) of [this bucket](https://github.com/Ash258/Shovel-Ash258)'s ~300 manifiests use `pre_uninstall`.

**Review by niheaven — APPROVED** [review]

**Pull request merged**
