### PR TITLE
Revert cygwin to version 2.8.1

### PR DESCRIPTION
**Pull request by rasa**
And removed the autoupdate section which is not useful.

### CODE REVIEW

**Comment by r15ch13** [comment]
How about using `nightly` as the version? The setup changes from time to time.

**Comment by rasa** [comment]
You're right. 2.8.1 is the version of Cygwin.dll, not setup*.exe.

**Comment by rasa** [comment]
The version number for setup*.exe is 2.881 per https://www.cygwin.com/ml/cygwin-announce/2017-07/msg00017.html

**Comment by rrelmy** [comment]
The setup.exe does check if there is an update available, so there is some sort of check for the latest version.

**Comment by r15ch13** [comment]
Can you find the URL via wireshark or the sourcecode? :)

**Comment by rrelmy** [comment]
I did not check the source but it most likely uses the `setup-version` property from the `setup.ini` which is present on each mirror
```
# This file was automatically generated at 2017-07-11 02:37:28 UTC.
#
# If you edit it, your edits will be discarded next time the file is
# generated.  See http://cygwin.com/setup.html for details.
release: cygwin
arch: x86_64
setup-timestamp: 1499740648
setup-version: 2.881
```

I took this from https://linux.rz.ruhr-uni-bochum.de/download/cygwin/x86_64/setup.ini

I do not know how fast the mirrors are updated and if there could be a difference between this file and the setup from the original site

**Comment by r15ch13** [comment]
Or we use the Taglist from the repository: https://cygwin.com/git/gitweb.cgi?p=cygwin-apps/setup.git;a=tags (regex: `release_([\d.]+)`)
The problem stays the same. When the setup.exe is not updated in time, the update thingy will use the wrong hash.

**Comment by rasa** [comment]
The canonical location for setup.ini is ftp://ftp.cygwin.com/pub/cygwin/x86/setup.ini

**Comment by r15ch13** [comment]
This works too https://cygwin.com/pub/cygwin/x86/setup.ini

**Pull request closed without merging**
