### PR TITLE
decompress.ps1: Refactored (w/ install.ps1, core.ps1) (edited)

### LINKED ISSUE #3120: 7zip@18.06: extract_dir error
PS H:\> scoop update 7zip
7zip: 18.06 (latest version)
Latest versions for all apps are installed! For more information try 'scoop status'
PS H:\> scoop uninstall 7zip
Uninstalling '7zip' (18.06).
'7zip' was uninstalled.
PS H:\> scoop install 7zip
Installing '7zip' (18.06) [64bit]
Loading 7z1806-x64.msi from cache
Checking hash of 7z1806-x64.msi ... ok.
Extracting 7z1806-x64.msi ... ERROR Could not find '7-Zip'! (error 16)

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop/issues/new?title=7zip%4018.06%3a+extract_dir+error

### PR DESCRIPTION
**Pull request by niheaven**
EDITED: Split PR, PART I

- Move Functions (to `decompress.ps1`)
  - `extract_zip` and `unzip_old` from `core.ps1`
  - `unpack_inno`, `extract_msi`, `lessmsi_config` and `extract_lessmsi` from `install.ps1`
- Modify Test
  - Move `unzip_old` test from `Scoop-Core.Tests.ps1` to `Scoop-Decompress.Tests.ps1`

Thanks for @Ash258 #3149, this could be part of it.

### CODE REVIEW

**Comment by Ash258** [comment]
I would rather see 3 PRs for each list item (instead of 1 huge) in small iteration windows. This increase error domain and could be hard to debug. So:

1. Move functions
    - Review
    - Merge
    - Wait for feedback of users (few days)
    - Repeat for next item

**Comment by niheaven** [comment]
Split PR and this is the one for moving function.

Other fix (rewrite functions, etc.) will be submitted after merged.

@Ash258 @r15ch13 @rasa

**Comment by r15ch13** [comment]
Working and ready for merge? Can't test right now.

**Comment by Ash258** [comment]
I am not sure if this change do not break installation of new scoop. Since only core is downloaded and extract_zip is called (https://github.com/lukesampson/scoop/blob/master/bin/install.ps1#L49)

@niheaven Have you tested installation?

**Comment by Ash258** [comment]
These "hacks" and continuality thinking about not breaking installation will not be needed when bucket extraction and standalone installer (https://github.com/scoopinstaller/install) is done and is not dependent on scoop's core implementation.

**Comment by Ash258** [comment]
LGTM. By static code review. Will fully test it in few minutes, after i arrive home.

**Comment by niheaven** [comment]
The new scoop installer uses the same method that I used here, and Expand-Archive for PS 5+, too.

**Comment by niheaven** [comment]
@Ash258 Does the test be passed?

**Comment by Ash258** [comment]
Tested basic scoop installation, manifest installation / updating.

**Pull request merged**
