### PR TITLE
Create png2jpeg.json

### PR DESCRIPTION
**Pull request by vaguiners**

### CODE REVIEW

**Comment by vaguiners** [comment]
Someone please help me to get sha1 from sourceforge download page.
view-source:https://sourceforge.net/projects/png2jpeg/files/win64/
d9a87cd875e33b6c6c7d8a902c4da54e6f11e807

**Comment by vaguiners** [comment]
Smaller, simpler (specific purpose) and there are differences in the license

I personally use this for my bat scripts

**Comment by vaguiners** [comment]
@r15ch13 
Linking ~\scoop\apps\png2jpeg\current => ~\scoop\apps\png2jpeg\1.0.1.7
Creating shim for 'png2jpeg'.
Can't shim 'png2jpeg.exe': File doesn't exist.

**Comment by rasa** [comment]
And shouldn’t the URLs be download....

**Comment by r15ch13** [comment]
Fixed with https://github.com/lukesampson/scoop/commit/1b89bc947d5c07c54afd83f2b688072773379003

**Pull request merged**
