### PR TITLE
Update youtube-dl.json

### PR DESCRIPTION
**Pull request by nishanthkarthik**
Updated version to 2015.07.07

### CODE REVIEW

**Comment by lukesampson** [comment]
Cool :+1:

**Comment by nishanthkarthik** [comment]
What if we write something that scrapes the version number from respective websites automatically? There is manual work involved for every program under scoop, but it would keep all software up to date. Can I start writing?

**Comment by lukesampson** [comment]
There's already a [checkver](https://github.com/lukesampson/scoop/blob/master/bin/checkver.ps1) script that does what I think you want to do. There's some usage info [here](https://github.com/lukesampson/scoop/issues/97), and the [app manifest reference](https://github.com/lukesampson/scoop/wiki/App-Manifests) has some more info about how to add this to your manifest.

**Comment by nishanthkarthik** [comment]
What I meant was,
say `gcc`, the current url in manifest is,
http://ufpr.dl.sourceforge.net/project/mingwbuilds/host-windows/releases/4.8.1/64-bit/threads-posix/seh/x64-4.8.1-release-posix-seh-rev5.7z
This 4.8.1 version number affects the url once a new update for gcc comes out. 

Why did I create this pull request to update the manifest? What if all manifests can be updated automatically?

**Comment by nishanthkarthik** [comment]
Thanks, found it.

**Comment by lukesampson** [comment]
Oh also, did you see @guillermooo's [script](https://github.com/lukesampson/scoop/issues/405) to update Dart manifest's automatically?

**Pull request merged**
