### PR TITLE
Add flyway

### PR DESCRIPTION
**Pull request by dsbert**
This pull request adds the flyway database migration tool

https://flywaydb.org/

### CODE REVIEW

**Comment by r15ch13** [comment]
What about the `sql`, `drivers` and `conf` directories? Is it necessary to make them persistent? Are they required or will they be created for each project?

**Comment by dsbert** [comment]
Is there a way to persist the files within the `drivers` directory without overwriting the entire folder upon update? Since that contains the `.jar` files that flyway is expecting to use, it would need to be merged with any updated versions.

**Comment by r15ch13** [comment]
Sadly this is not possible. 😞

**Comment by dsbert** [comment]
Then for now I think the best compromise is to persist the `conf`, `jars`, and `sql` folders.

**Pull request merged**
