### PR TITLE
upgrade dart to 1.11.3

### PR DESCRIPTION
**Pull request by devoncarew**
Upgrade the Dart SDK from 1.11.1 to 1.11.3.

### CODE REVIEW

**Comment by devoncarew** [comment]
also cc'ing @guillermooo

**Comment by guillermooo** [comment]
lgtm!

Also: https://gist.github.com/guillermooo/f579fdb84aab4bc488da

It's a script to automate the manifest update.

It needs to be fixed to pin the version to a real version number, though.

**Comment by devoncarew** [comment]
Ah cool!

I just found this guy: https://github.com/lukesampson/scoop-extras/blob/master/dart-dev.json. I didn't know there was a dart-dev install available. It looks like that needs updating as well

**Comment by guillermooo** [comment]
I'll take a look at that.

**Comment by deevus** [comment]
:+1:

**Pull request merged**
