### PR TITLE
Add armor (https://github.com/labstack/armor) and tunnel (https://github.com/labstack/tunnel)

### PR DESCRIPTION
**Pull request by vishr**
Signed-off-by: Vishal Rana <vr@labstack.com>

### CODE REVIEW

**Comment by r15ch13** [comment]
Cool projects! 👍

Since you are the developer, may I ask you to add a checksum file to the Github releases? 😁
This would reduce update speed and bandwidth usage.

**Comment by h404bi** [comment]
FYI.

git:
- https://github.com/git-for-windows/git/releases
- https://github.com/lukesampson/scoop/blob/920ee0a7f00e4ea5c0f9e823a69e18e4b9444db6/bucket/git.json#L56-L59

**Comment by r15ch13** [comment]
restic: [Github](https://github.com/restic/restic/releases) / [restic.json](https://github.com/lukesampson/scoop/blob/master/bucket/restic.json)

You could run `sha256sum` in your CI script if you use automated releases.
`sha256sum armor* > SHA256SUMS`

**Comment by vishr** [comment]
Thanks, I will look into it.

**Comment by r15ch13** [comment]
A small project where I use `glide` and `gox` to create deterministic builds and get pushed by AppVeyor to Github.
https://github.com/r15ch13/acbf/blob/master/appveyor.yml

**Pull request merged**
