### PR TITLE
Preventing Go users from having their GOPATH changed when upgrading.

### LINKED ISSUE #1786: Go install changing GOPATH to the wrong directory
This guy seems to be the culprit:
https://github.com/lukesampson/scoop/commit/f186280d19fc83fb799432b537f1ec321ce2423a#diff-e79f298f61bd1fc45ecc46043d952492

My GOPATH was unexpectedly changed from $HOME/go to something unconventional with the upgrade to 1.9.2.

### PR DESCRIPTION
**Pull request by barrongineer**
Leaving the GOPATH alone in case they've already got one set. Go defaults to $HOME/go anyway.

Fixes #1786

### CODE REVIEW

**Comment by r15ch13** [comment]
The main goal of @matthewjberger was to add the `bin` directory for installed packages to the `PATH` via scoop.
`env_add_path` doesn't allow a path outside the scoop directory, so we don't mess up someones `PATH` variable too much. The only way was to move the `GOPATH` inside the scoop peristent directory.

**Comment by barrongineer** [comment]
The problem is that after running `scoop update go`, all of a sudden your projects don't compile. Not to mention most ppl use $HOME/go, that's why Go defaults to it.

I don't think the scoop install should do anything beyond what a manual download / install would.

**Comment by r15ch13** [comment]
This one uses `add_first_in_path` and `remove_from_path` to add and remove the `$env:USERPROFILE\\go\\bin` from the `PATH`.

```json
{
    "version": "1.9.2",
    "homepage": "https://golang.org",
    "license": "https://golang.org/LICENSE",
    "persist": "go",
    "extract_dir": "go",
    "env_set": {
        "GOROOT": "$dir"
    },
    "env_add_path": "bin",
    "installer": {
        "script": "add_first_in_path \"$env:USERPROFILE\\go\\bin\" $global"
    },
    "uninstaller": {
        "script": "remove_from_path \"$env:USERPROFILE\\go\\bin\" $global"
    },
    "architecture": {
        "64bit": {
            "url": "https://storage.googleapis.com/golang/go1.9.2.windows-amd64.zip",
            "hash": "682ec3626a9c45b657c2456e35cadad119057408d37f334c6c24d88389c2164c"
        },
        "32bit": {
            "url": "https://storage.googleapis.com/golang/go1.9.2.windows-386.zip",
            "hash": "35d3be5d7b97c6d11ffb76c1b19e20a824e427805ee918e82c08a2e5793eda20"
        }
    },
    "checkver": "Build version go([\\d\\.]+)\\.",
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://storage.googleapis.com/golang/go$version.windows-amd64.zip"
            },
            "32bit": {
                "url": "https://storage.googleapis.com/golang/go$version.windows-386.zip"
            }
        },
        "hash": {
            "url": "$url.sha256"
        }
    },
    "notes": "
        Your GOROOT has been set to: $dir
        You can run 'go env GOROOT' to view this at any time.
        \"$env:USERPROFILE\\go\\bin)\" has been added to your PATH.
    "
}
```

**Comment by barrongineer** [comment]
What is `add_first_in_path`? I can't seem to find it in the docs.

**Comment by r15ch13** [comment]
Undocumented function that is used by [`env_add_path`](https://github.com/lukesampson/scoop/blob/master/lib/install.ps1#L804)

**Pull request merged**
