### PR TITLE
Update dotnet to 1.1.1

### PR DESCRIPTION
**Pull request by inosik**
This updates the `dotnet` manifest to v1.1.1. Or, at least that's the version the ZIP-file has in it's name.

@yunspace @jggrant do these changes look right to you?

### CODE REVIEW

**Comment by lukesampson** [comment]
Have you noticed how `dotnet --version` reports version 1.0.1? It's confusing that the .zip has 1.1.1, but I think we should probably go with what the exe reports instead. Thoughts?

**Comment by rrelmy** [comment]
OMG, that's a mess. [Microsoft](https://www.microsoft.com/net/download/core#/sdk) calls it **.NET Core SDK (contains .NET Core 1.0 and 1.1)**.
Inside `shared/Microsoft.NETCore.App` are two directories for 1.0.4 and 1.1.1 also with a `dotnet.exe` too. 🤣 
If one of those binaries would be interesting the `bin` reference should be updated inside the manifest.

_The dotnet.exe binaries inside `/shared/` do not output a version if executed with the `--version` flag._ 🙈

**Comment by lukesampson** [comment]
Errrrr.... okay! Thanks for looking into it @rrelmy. Maybe `1.1.1` isn't such a bad idea after all??

**Comment by rrelmy** [comment]
Without `--version` the dotnet.exe in the root reports version 1.1.0. The binary inside the shared/1.1.1 directory should the same version and build, but not with `--version` and has also a different hash.
Can someone explain?

dotnet-whatthefuck

**Comment by lukesampson** [comment]
It looks like [we're not the only ones confused](https://github.com/dotnet/cli/issues/3773)! 

It seems like `--version` is the CLI version, and the version printed without args is the version of the shared framework.

I'm still not sure what version we should use for Scoop...

**Comment by rrelmy** [comment]
Unbelievable, what a mess.  Ok for me to merge, even I am not really sure if the version should be 1.1.0 or 1.1.1.

As inosik said, 
>at least that's the version the ZIP-file has in it's name

**Comment by inosik** [comment]
Thanks for merging!

> Unbelievable, what a mess.

The department for version confusion in Redmond did a really good on this one :smile:

**Pull request merged**
