### PR TITLE
Changing miktex url to ctan!

### PR DESCRIPTION
**Pull request by yigitemres**
Miktex url is not working, we have to use CTAN. #2129

### CODE REVIEW

**Comment by r15ch13** [comment]
We could fix the link to ftp.fau.de, it's the only mirror that supports HTTPS.
https://ftp.fau.de/ctan/systems/win32/miktex/setup/

**Comment by brandon93s** [comment]
Existing urls appear to be working now.

**Comment by yigitemres** [comment]
@r15ch13 and @brandon93s Sorry for late answers. If existing urls are still working then I will close this pull request.

**Comment by r15ch13** [comment]
As long as the mirrors don't use HTTPS they will fail.
I would recommend using https://ftp.fau.de/ instead of downgrading to HTTP

**Comment by yigitemres** [comment]
@r15ch13 I was looking for something and I forget to push it. Thx for double reminder and suggestion! 🥂

**Pull request merged**
