### PR TITLE
Migrate selected CLI apps from rasa/scoops (fixes #1358)

### LINKED ISSUE #1358: [FR] Move selected apps from rasa to scoop
Per [deevus's comment](https://github.com/lukesampson/scoop/commit/c496fa2cdd6c47f87cc7b5bfe951573851a60a8b#commitcomment-21081646), here's a list of open source<sup><a href="#*">*</a></sup> CLI apps that I'm willing to PR from [rasa/scoops](https://github.com/rasa/scoops), in the main scoop bucket:

|Name|Version|Description|License|
|----|-------|-----------|-------|
|[cdrtools](https://sourceforge.net/projects/tumagcc/ "https://sourceforge.net/projects/tumagcc/")|[3.01](https://sourceforge.net/projects/tumagcc/ "https://sourceforge.net/projects/tumagcc/")|Burn and read CDs, DVDs, and Blu-ray discs|[CDDL-1.0](https://opensource.org/licenses/CDDL-1.0 "https://opensource.org/licenses/CDDL-1.0")/[GPL-2.0](https://opensource.org/licenses/GPL-2.0 "https://opensource.org/licenses/GPL-2.0")/[LGPL-2.1](https://opensource.org/licenses/LGPL-2.1 "https://opensource.org/licenses/LGPL-2.1")|
|[handbrake_cli](https://handbrake.fr/ "https://handbrake.fr/")|[1.0.3](https://handbrake.fr/downloads2.php "https://handbrake.fr/downloads2.php")|Convert videos with CLI program|[GPL-2.0](https://opensource.org/licenses/GPL-2.0 "https://opensource.org/licenses/GPL-2.0")|
|[infounzip](http://www.info-zip.org/ "http://www.info-zip.org/")|[6.00](http://www.info-zip.org/ "http://www.info-zip.org/")|Unzip compression utility|[Link](http://www.info-zip.org/pub/infozip/license.html "http://www.info-zip.org/pub/infozip/license.html")|
|[infozip](http://www.info-zip.org/ "http://www.info-zip.org/")|[3.0](http://www.info-zip.org/ "http://www.info-zip.org/")|Zip compression utilities|[Link](http://www.info-zip.org/pub/infozip/license.html "http://www.info-zip.org/pub/infozip/license.html")|
|[metastore](https://github.com/rasa/metastore "https://github.com/rasa/metastore")|[95d4e2d](https://github.com/rasa/metastore/releases/latest "https://github.com/rasa/metastore/releases/latest")|Store and restore metadata from a filesystem|[GPL-2.0](https://opensource.org/licenses/GPL-2.0 "https://opensource.org/licenses/GPL-2.0")|
|[nc](https://eternallybored.org/misc/netcat/ "https://eternallybored.org/misc/netcat/") (aka netcat)|[1.12](https://eternallybored.org/misc/netcat/ "https://eternallybored.org/misc/netcat/")|Read and write from/to network connections|[GPL-2.0](https://opensource.org/licenses/GPL-2.0 "https://opensource.org/licenses/GPL-2.0")|
|[openssl10x](http://slproweb.com/products/Win32OpenSSL.html "http://slproweb.com/products/Win32OpenSSL.html")|[1.0.2k](http://slproweb.com/products/Win32OpenSSL.html "http://slproweb.com/products/Win32OpenSSL.html")|TLS/SSL toolkit (1.0.x branch)|[Link](https://www.openssl.org/source/license.html "https://www.openssl.org/source/license.html")|
|[pciutils](https://eternallybored.org/misc/pciutils/ "https://eternallybored.org/misc/pciutils/")|[3.4.0](https://eternallybored.org/misc/pciutils/ "https://eternallybored.org/misc/pciutils/")|Inspect and manipulate configuration of PCI devices|[GPL-2.0](https://opensource.org/licenses/GPL-2.0 "https://opensource.org/licenses/GPL-2.0")|
|[poppler](http://blog.alivate.com.au/poppler-windows/ "http://blog.alivate.com.au/poppler-windows/")|[0.51](http://blog.alivate.com.au/poppler-windows/ "http://blog.alivate.com.au/poppler-windows/")|PDF rendering library|[GPL-3.0](https://opensource.org/licenses/GPL-3.0 "https://opensource.org/licenses/GPL-3.0")|
|[smartmontools](https://www.smartmontools.org/ "https://www.smartmontools.org/")|[6.5-1](https://sourceforge.net/projects/smartmontools/files/smartmontools/ "https://sourceforge.net/projects/smartmontools/files/smartmontools/")|Read SMART data from disks|[GPL-2.0](https://opensource.org/licenses/GPL-2.0 "https://opensource.org/licenses/GPL-2.0")|
|[sslscan](https://github.com/rbsec/sslscan "https://github.com/rbsec/sslscan")|[1.11.0](https://github.com/rbsec/sslscan "https://github.com/rbsec/sslscan")|Discover supported cipher suites for SSL/TLS enabled services|[GPL-3.0](https://opensource.org/licenses/GPL-3.0 "https://opensource.org/licenses/GPL-3.0")|
|[tesseract](https://github.com/UB-Mannheim/tesseract/wiki "https://github.com/UB-Mannheim/tesseract/wiki")|[3.05.00](https://github.com/UB-Mannheim/tesseract/wiki "https://github.com/UB-Mannheim/tesseract/wiki")|OCR engine developed by Google|[Apache-2.0](https://opensource.org/licenses/Apache-2.0 "https://opensource.org/licenses/Apache-2.0")|
|[tesseract_experimental](https://github.com/UB-Mannheim/tesseract/wiki "https://github.com/UB-Mannheim/tesseract/wiki")|[4.00.00](https://github.com/UB-Mannheim/tesseract/wiki "https://github.com/UB-Mannheim/tesseract/wiki")|OCR engine developed by Google|[Apache-2.0](https://opensource.org/licenses/Apache-2.0 "https://opensource.org/licenses/Apache-2.0")|
|[tidy](http://www.html-tidy.org/ "http://www.html-tidy.org/")|[5.2.0](http://www.html-tidy.org/ "http://www.html-tidy.org/")|Tidy HTML and XML files|[Link](http://www.html-tidy.org/documentation/#license "http://www.html-tidy.org/documentation/#license")|
|[unrar](http://www.rarlab.com/ "http://www.rarlab.com/")|[5.40](http://www.rarlab.com/download.htm "http://www.rarlab.com/download.htm")|Uncompress RAR files|[Freeware](https://en.wikipedia.org/wiki/Freeware "https://en.wikipedia.org/wiki/Freeware")|
|[wkhtmltopdf](http://wkhtmltopdf.org/ "http://wkhtmltopdf.org/")|[0.12.4](http://wkhtmltopdf.org/downloads.html "http://wkhtmltopdf.org/downloads.html")|Render HTML into PDF|[LGPL-3.0](https://opensource.org/licenses/LGPL-3.0 "https://opensource.org/licenses/LGPL-3.0")|
|[x264-10bit](https://www.videolan.org/developers/x264.html "https://www.videolan.org/developers/x264.html")|[17.01.30](https://www.videolan.org/developers/x264.html "https://www.videolan.org/developers/x264.html")|H.264/MPEG-4 AVC video encoder (10 bit)|[GPL-2.0](https://opensource.org/licenses/GPL-2.0 "https://opensource.org/licenses/GPL-2.0")|
|[x264-8bit](https://www.videolan.org/developers/x264.html "https://www.videolan.org/developers/x264.html")|[17.01.30](https://www.videolan.org/developers/x264.html "https://www.videolan.org/developers/x264.html")|H.264/MPEG-4 AVC video encoder (8 bit)|[GPL-2.0](https://opensource.org/licenses/GPL-2.0 "https://opensource.org/licenses/GPL-2.0")|
|[xmlstarlet](http://xmlstar.sourceforge.net/ "http://xmlstar.sourceforge.net/")|[1.6.1](https://sourceforge.net/projects/xmlstar/files/ "https://sourceforge.net/projects/xmlstar/files/")|Transform, query, validate, and edit XML files|[MIT](https://opensource.org/licenses/MIT "https://opensource.org/licenses/MIT")|

I would suggest we rename infozip to zip, and infounzip to unzip.
Also, I think renaming x264-8bit to simply x264 makes sense.

Thoughts? Did I miss anything else that should be included?

<a name="*"/><sup>*</sup> `unrar` provides its [source code](http://www.rarlab.com/rar/unrarsrc-5.4.5.tar.gz), but its [license](https://github.com/tony2001/unrar/blob/master/license.txt) is not [OSI-approved](https://opensource.org/licenses).

### PR DESCRIPTION
**Pull request by rasa**
Sorry about the errant merge commit.

### CODE REVIEW

**Comment by r15ch13** [comment]
Poppler could be autoupdated.

Use `extract_dir` for xmlstarlet to fix the validation error. (`bin` will not be updated automatically)
```
    "autoupdate": {
        "extract_dir": "xmlstarlet-$version",
        "url": "https://sourceforge.net/projects/xmlstar/files/xmlstarlet/$version/xmlstarlet-$version-win32.zip"
    },
    "bin": "xml.exe",
    "extract_dir": "xmlstarlet-1.6.1",
```

**Comment by rasa** [comment]
I added an `autoupdate` to poppler, but since the month is in the URL, it will fail come April.

**Comment by r15ch13** [comment]
`"checkver": "Latest.*uploads/(?<date>\\d{4}/\\d{2})/poppler-(?<version>[\\d.]+)_x86.7z",`
and
```
    "autoupdate": {
        "url": "http://blog.alivate.com.au/wp-content/uploads/$matchDate/poppler-$version_x86.7z"
    },
```
should do the trick :smile:

**Comment by rasa** [comment]
Cool!

**Comment by rasa** [comment]
So `$matchDate` and `$version`, not
`$matchDate` and `$matchVersion`, or
`$date` and `$version`?

**Comment by r15ch13** [comment]
`$version` is always available. `$match*` only for capturing groups you defined. See: https://github.com/lukesampson/scoop/wiki/App-Manifest-Autoupdate#reference

**Comment by rasa** [comment]
Very cool (sorry, I should have RTFM).

**Comment by lukesampson** [comment]
This is great! Okay to merge now?

**Comment by rasa** [comment]
GTG from my POV, but I will redo, if you want the PR cleaner.

**Pull request merged**
