### PR TITLE
 BREAKING CHANGE: drop main bucket 

### PR DESCRIPTION
**Pull request by h404bi**
follow up https://github.com/lukesampson/scoop/pull/3060

### CODE REVIEW

**Comment by h404bi** [comment]
untested

**Comment by Ash258** [comment]
This could be easily done after merging develop to master.

This nested bucket will not be used by any function. So you could easily push develop in master (with actual state) and then after few hours / days remove nested bucket from master.

Do this later makes more sense if anything really bad happened. Since there will be smaller diff while reverting 😂

**Comment by niheaven** [comment]
So the other one is MUST, this one is MAY...

**Comment by h404bi** [comment]
So when the new main bucket exists with nested bucket, which one would be used?

**Comment by niheaven** [comment]
The new one, since bucket functions find manifests in buckets dir, and with app name likes `7zip`, it looks at `main`.

**Comment by Ash258** [comment]
Always that one from `Find-Manifest` function, which has default main bucket located inside `$bucketsdir`

**Pull request closed without merging**
