### PR TITLE
Add manifest for kitematic

### PR DESCRIPTION
**Pull request by caveman-dick**
Tested autoupdate and works fine:

image

### CODE REVIEW

**Comment by r15ch13** [comment]
This is better suited for the [extras bucket](https://github.com/lukesampson/scoop-extras). Please create a new PR over there. 👍 
The `depends` property can be removed if empty.

**Comment by caveman-dick** [comment]
@r15ch13 I can move over no problem, I'm just wondering why that rather than in the main bucket? Because it's not a widely known/used tool?

**Comment by r15ch13** [comment]
Because the main bucket is mostly for self-containing CLI programs. Everything with a Window goes to extras 😄

**Comment by caveman-dick** [comment]
Moved to extras as requested: https://github.com/lukesampson/scoop-extras/pull/692

**Pull request closed without merging**
