### PR TITLE
cmake 3.8 update

### PR DESCRIPTION
**Pull request by jfmherokiller**

### CODE REVIEW

**Comment by r15ch13** [comment]
Was already added to the extras bucket with this pr https://github.com/lukesampson/scoop-extras/pull/361

**Comment by lukesampson** [comment]
Thanks for this, but we try to keep the main bucket for stable releases only. As @r15ch13 mentioned, @berwyn's 3.8-rc1 version is already in extras. You can install it with `scoop bucket add extras; scoop install cmake-rc`.

I'll close this PR for now, but please submit 3.8 again when it goes stable.

**Comment by jfmherokiller** [comment]
thanks for letting me know but how do i install the cmake version in the extras bucket because i need it for vcpkg

**Comment by lukesampson** [comment]
```
scoop bucket add extras
scoop install cmake-rc
```

**Comment by jfmherokiller** [comment]
thanks

**Pull request closed without merging**
