### PR TITLE
Fix Apache version to 2.4.17 (2.4.16 outdated)

### PR DESCRIPTION
**Pull request by Sandex**

### CODE REVIEW

**Comment by lukesampson** [comment]
Thanks :)

**Comment by mdaronco** [comment]
Hi Luke Sampson!

Are there any packages that you can install with scoop in order to compile
and run C++ within the powershell?  To this point I've been using the g++
compiler within a Cygwin shell.

Cheers

Matt Daronco

**Comment by lukesampson** [comment]
Hi Matt,

There are packages for gcc
<https://github.com/lukesampson/scoop/blob/master/bucket/gcc.json> (v4.8.1)
and gcc45
<https://github.com/lukesampson/scoop/blob/master/bucket/gcc45.json>
(v4.5.1) and visualc
<https://github.com/lukesampson/scoop-extras/blob/master/visualc.json> (Visual
C++ 2010 - you need to run "scoop bucket add extras" before running "scoop
install visualc").

I'm clueless when it comes to C++ — I did have some success compiling Rust
with GCC <http://blog.lukesampson.com/rust-on-windows> but I had to jump
into MSYS for the configure and make. If you know a way to make this a
better experience through Powershell, we'd be interested to hear.

**Comment by mdaronco** [comment]
Awesome, I'll be sure to let y'all know if I can find anything.

On another note, can you explain the gvim app, and how it differs from
vim?  I primarily use Go, javascript, etc. (web developer) for work, but
can't seem to have Powershell recognize Go syntax when opening a .go file,
for example, "vim models/users.go".  I am sort of limited to Windows for
school, but usually work within a Mac or Linux environment.  Thanks.

Also, how long did it take you to amass the knowledge needed to create the
Scoop project? (I know there are several contributors on Github).  I think
it's pretty awesome, as seeing as I am a big fan of Homebrew for Mac.

**Comment by lukesampson** [comment]
Thanks, sent you an email :)

**Pull request merged**
