### PR TITLE
service management

### PR DESCRIPTION
**Pull request by deepakSP**
we have two alias - srvman and service

some useful command for development

sudo service start apache

sudo service stop nginx

sudo service restart php-cgi

sudo service add <file.exe/file.sys> [service name] [display name] [/type:<service type>] [/start:<start mode>] [/interactive:no] [/overwrite:yes]

sudo service delete mysql

if you want to use add, edit or delete command please refer official documents. - http://tools.sysprogs.org/srvman/

### CODE REVIEW

**Comment by lukesampson** [comment]
Cool! This is a great start. A couple of small things:

* Can you rename the file to srvman.json? Scoop packages go by the name of the program rather than the executables. It looks like it would still be discoverable with `scoop search service` since you're adding that alias.
* The app veyor build is failing because we have a test to ensure all files end with newlines. If you can fix that up it helps me merge quicker.

**Comment by deepakSP** [comment]
sure, i am checking veyor

**Comment by deepakSP** [comment]
done 👍

**Comment by lukesampson** [comment]
Great! By the way, you can also run the tests locally with the `bin/test.ps1` command in the scoop source directory.

**Pull request merged**
