### PR TITLE
PowerShell script to locate Java on Windows

### PR DESCRIPTION
**Pull request by se35710**
Optionally sets JAVA_HOME and JRE_HOME

### CODE REVIEW

**Comment by lukesampson** [comment]
Thanks. I think this would be better in the [extras](https://github.com/lukesampson/scoop-extras) bucket — do you mind resubmitting there please?

**Comment by tresf** [comment]
If not already, this script should also detect the 32-bit registry version, such as when running 32-bit Java on 64-bit Windows (Windows-on-Windows64, aka WOW64)

**Comment by se35710** [comment]
@lukesampson Sure, but I do think it is a good idea to include it in the main bucket. Some installers (Flexeras Install Anywhere for example) depends on `JAVA_HOME` being set, even if java.exe is available in `PATH`. Instead of using `”depends”: “OpenJDK”` and download 100 MB, this 11 kB script will find a suitable Java with `"depends": "find-java"`. Java (when installed outside of scoop) does not set `JAVA_HOME`, and its install directories is also version dependant. For that reason I think this helper script could be helpful.

For manifests, like the Tomcat one, the catalina shim could be updated to find a suitable Server JRE, for all the Eclipse manifests a fullblown JDK, etc.

Another more complicated way would to extend the same functionality within scoop itself, and if that is something that is preferred, I offer my help.

@tresf I’ve updated the script now so it searches through the WoW registry node too. `-Achitecture $arch` could be used in scoop manifests to force `$arch` for 32 bit Java programs running on 64 bit Windows.

**Comment by lukesampson** [comment]
I thought we had removed all the instances of `"depends": "openjdk"` — maybe we missed some.

The new approach is to use `"suggest"` instead of `"depends"` for Java SDKs. It leaves the choice up to the developer, leaves open the possibility of a non-Scoop installed JDK, and it's not hard to run an extra `scoop install oraclejdk`.

**Pull request closed without merging**
