### PR TITLE
Global reset

### PR DESCRIPTION
**Pull request by sestegra**
Add global option to reset command

### CODE REVIEW

**Comment by gutierri** [comment]
@lukesampson ?

**Comment by lukesampson** [comment]
To me, reset doesn't make much sense for global apps. Global apps are for every user on the system. The reset command is for switching between different versions of an app, and that could cause chaos if an administrator is switching versions on everyone. I think this is the sort of thing you want to control just for yourself as a developer.

**Comment by deevus** [comment]
I'd be interested to know the use case in which wanting to reset a global app comes up. Perhaps @sestegra can shed some light on this?

**Comment by c33s** [comment]
should be handled some way, currently installing ruby & ruby19 globally works but switching wont work. you should either allow installing both and allow global switching or disallow install both versions

**Pull request closed without merging**
