### PR TITLE
[WIP] Simple GitHub manifest generation

### PR DESCRIPTION
**Pull request by Elvyria**
It never was so easy to create GitHub manifest

How to test:
`scoop create https://github.com/mridgers/clink`

Result (with prerelease choice):
```
{
    "homepage": "mridgers.github.io/clink",
    "description": "Bash's powerful command line editing in cmd.exe",
    "license": {
        "identifier": "GPL-3.0"
    },
    "version": "1.0.0a1",
    "url": "https://github.com/mridgers/clink/releases/download/1.0.0a1/clink-1.0.0a1.823d84.zip",
    "hash": "902a4c3cb3947792877322b772b71a91ff1b775e8a1ae2295a5563cd9209220c",
    "extract_dir": "clink-1.0.0a1.823d84",
    "bin": [
        "clink.bat",
        "clink_x64.exe",
        "clink_x86.exe"
    ],
    "depends": "",
    "checkver": {
        "github": "https://github.com/mridgers/clink"
    },
    "autoupdate": {
        "extract_dir": "clink-$version.823d84",
        "url": "https://github.com/mridgers/clink/releases/download/$version/clink-$version.823d84.zip"
    }
}
```

### Todo:
- [x] Fix position of names in result file (if possible)
- [x] Do much more tests with different projects to find out bugs (20 repos where tested)
- [x] Hash, extract_dir, bin
- [x] Make this mess understandable to other people

### CODE REVIEW

**Comment by h404bi** [comment]
I would like to suggest to create a reusable script (like `generate-github-manifest.ps1`) under the `bin` directory, so other bucket could just reuse the script to create github manifest in their bucket repository, just like `checkver` and `auto-pr` scripts, etc, instead of creating a scoop sub-command.

**Comment by Elvyria** [comment]
I don't really see the point of duplicating code over buckets, since it creates manifest in your current console directory.  The point of `scoop create` command was to help users create their own manifest template it was in scoop for ages and it's not like i added command here. If scoop maintainers agreed that it would be better to create separate script under bin, i'll transfer all code to a new script and leave `scoop-create.ps1` without changes.

**Comment by r15ch13** [comment]
Hm, maybe it could be more interactive?
Show the data we found and ask a bunch of questions. :grin:

Reduced the asset part to this:
```powershell
# snip
    if ($release.assets) {
        $windows_ext = ".(zip|rar|7z|msi|exe)"
        $prefered_ext = ".(zip|7z|rar)"

        $manifest.version = $release.tag_name

        if($release.assets) {
            if(confirm 'Has 64bit and 32bit releases?') {
                $asset_32 = choose_item $release.assets 'Choose 32bit release' 'name'
                $asset_64 = choose_item $release.assets 'Choose 64bit release' 'name'
                write-host 'Downloading releases and calculation checksums ...'
                url $asset_32.browser_download_url $asset_64.browser_download_url
                install_info $asset_32.browser_download_url "32bit"
                install_info $asset_64.browser_download_url "64bit"
            } else {
                $asset = choose_item $release.assets 'Choose release' 'name'
                url $asset.browser_download_url $null
                install_info $asset.browser_download_url $null
            }
        }

    } else { # If there's no releases try to find tags
# snip
```
This one worked well with:
- https://github.com/junegunn/fzf-bin

Issues with:
- https://github.com/danmar/cppcheck tries to extract `msi` file (check [file_requires_7zip()](https://github.com/lukesampson/scoop/blob/0cd842309e9f7625af0d6c032e411d06e6a1e4b0/lib/decompress.ps1#L16))

**Comment by Elvyria** [comment]
@r15ch13 This pull is almost ready for merge and i want to hear your position about creating separate file for this thing, if you're positive about it i guess there's no need in updating wiki page for manifest creation and separating code would be the final step here.

**Comment by rasa** [comment]
Why are you closing? In my opinion this is excellent work that would benefit us. I’m sorry we didn’t work harder to include it.

**Pull request closed without merging**
