### PR TITLE
invoke-build 3.2.4

### PR DESCRIPTION
**Pull request by nightroman**

### CODE REVIEW

**Comment by rrelmy** [comment]
Why is there no autoupdate? :-)

**Comment by nightroman** [comment]
From the question I can guess I miss some feature. What is this?

**Comment by lukesampson** [comment]
Rémy is referring to [this](https://github.com/lukesampson/scoop/wiki/App-Manifest-Autoupdate) new feature that can update your manifests automatically when there is a new version. It's optional, but highly recommended.

**Comment by nightroman** [comment]
I see, thank you. It looks like a handy feature. I will try on my next update.

**Comment by r15ch13** [comment]
Already added that after the merge https://github.com/lukesampson/scoop/commit/42dfe611889e4c1339125ae2555d83405f196d65 😊

**Pull request merged**
