### PR TITLE
[manifest] Present new Out-Manifest and Get-Manifest function

### PR DESCRIPTION
**Pull request by Ash258**
First part of YAML manifests support.

These wrapper functions will help with integrating new manifest types and make code a bit cleaner.

#2715

### CODE REVIEW

**Comment by niheaven** [comment]
Why not use `parse_json` as warpper function of `Get-Manifest` so `parse_json` could be deleted after no reference exist?

**Comment by Ash258** [comment]
Because i want to extend that funtion get-manifest to something like this:

```powershell
function Get-M {
switch ($extensionOfFile) {
    'yaml|'yml' {
        $man parse_yml
     }
	default {
		$man = parse_json
	}
}
return $man
}
```

**Comment by Ash258** [comment]
https://github.com/Ash258/scoop/blob/35af9a326aa6c542f75407f2ea7ca02e11b37634/lib/manifest.ps1#L59-L70
This is old implementation which i will port to use switch maybe

**Comment by niheaven** [comment]
Maybe as follow:

```powershell
function parse_json {
    Get-Manifest ...
}
function Get-Manifest (..., [Switch]$XML) {
    if ($XML) {
        ...
    } else {
        ...
    }
}
```

**Comment by Ash258** [comment]
I do not want to add switch parameter. I will add yaml support and someone could add toml support, so new parameter need to be set, which is not good.

I rather put filepath and then determine file type and execute correct parsing function.

**Comment by Ash258** [comment]
Maybe move `parse_json` into `lib\json.ps1`? 🤔

**Comment by niheaven** [comment]
And a new `xml.ps1`

**Comment by Ash258** [comment]
Exactly.
Try to move towards strict and more divergent /independent modules.

**Pull request closed without merging**
