### PR TITLE
fix(install): Prefer internal functions over external scoop command

### LINKED ISSUE #3616: travis-ci: The term 'scoop' is not recognized as the name of a cmdlet, function, script file, or operable program.
.travis.yml
```
language: c
matrix:
  include:
    - os: windows
      install:
        - powershell "Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser"
        - powershell "iex (new-object net.webclient).downloadstring('https://get.scoop.sh')"
        - export PATH="$PATH:"~/scoop/shims/
        - scoop install make nodejs yarn
    - os: osx
      osx_image: xcode10.3
      addons:
        homebrew:
          packages:
            - make
            - nodejs
            - npm
            - yarn
    - os: linux
      dist: bionic
      sudo: required
      addons:
        apt:
          sources:
            - sourceline: 'deb https://dl.yarnpkg.com/debian/ stable main'
              key_url: 'https://dl.yarnpkg.com/debian/pubkey.gpg'
          packages:
            - make
            - nodejs
            - npm
            - yarn
script:
  - make all
  - make test
```

log
```
$ scoop install make nodejs yarn
Installing 'make' (4.2.1) [64bit]
scoop : The term 'scoop' is not recognized as the name of a cmdlet, function, script file, or operable program. Check 
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\travis\scoop\apps\scoop\current\lib\core.ps1:802 char:21
+     $last_update = (scoop config lastupdate)
+                     ~~~~~
    + CategoryInfo          : ObjectNotFound: (scoop:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
scoop : The term 'scoop' is not recognized as the name of a cmdlet, function, script file, or operable program. Check 
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\travis\scoop\apps\scoop\current\lib\core.ps1:818 char:9
+         scoop config lastupdate $now.ToString('o')
+         ~~~~~
    + CategoryInfo          : ObjectNotFound: (scoop:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
scoop : The term 'scoop' is not recognized as the name of a cmdlet, function, script file, or operable program. Check 
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\travis\scoop\apps\scoop\current\libexec\scoop-install.ps1:71 char:5
+     scoop update
+     ~~~~~
    + CategoryInfo          : ObjectNotFound: (scoop:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
Downloading https://downloads.sourceforge.net/project/ezwinports/make-4.2.1-without-guile-w32-bin.zip (336.5 KB)...
Checking hash of make-4.2.1-without-guile-w32-bin.zip ... ok.
Extracting make-4.2.1-without-guile-w32-bin.zip ... done.
Linking ~\scoop\apps\make\current => ~\scoop\apps\make\4.2.1
Creating shim for 'make'.
...
```

### PR DESCRIPTION
**Pull request by Ash258**
- Closes #3616

I am not sure If I should add default to #L818. It could be empty string, but result `$null` should be same. Also this config have to exists all the time, unless use will delete it manually or remove config file.

### CODE REVIEW

**Comment by r15ch13** [comment]
It was changed to use `scoop config` in https://github.com/lukesampson/scoop/pull/1699
because `get_config()` doesn't "reload" the configfile.
To not break the update command it would require running `load_cfg()` before both(?) calls.

**Comment by Ash258** [comment]
Two options.

1. `$PSscriptRoot\..\bin\scoop.ps1 config`
1. `load_cfg; get_config`

**Comment by r15ch13** [comment]
`$PSscriptRoot\..\bin\scoop.ps1 config` keeps it more like it is now. Without adding other stuff like the `$configFile` variable.

Option 1.

**Comment by Ash258** [comment]
Or slightly edited option 1. `$PSScriptRoot\scoop-config.ps1` as it will remove overhead from calling main scoop wrapper.

**Pull request closed without merging**
