### PR TITLE
Fixed Bazel dependencies and added environment variable.

### PR DESCRIPTION
**Pull request by excitoon**
See #2186.

Zip is taken from http://www.paehl.com and repackaged to zip (sic!) in order to avoid `7z` dependency.

### CODE REVIEW

**Comment by r15ch13** [comment]
Is there a reason for changing the `zip` version?
Depending on just `python27` will fail. It should be `versions/python27` or add it as a suggestion.

**Comment by rasa** [comment]
I would suggest we push the zip change to the versions bucket as 3.1d is a beta version

**Comment by excitoon** [comment]
Okay, I will try to find fresh non-beta version of zip. Current zip in main is outdated. Will come back soon.

**Comment by rasa** [comment]
I’m pretty sure a dependency on 7z is fine.

**Comment by rasa** [comment]
Added the zip 3.1 beta at https://github.com/scoopinstaller/versions/commit/db12fed879f13cc253d2281dcb8725fae4c2892c

**Comment by excitoon** [comment]
Thanks!

**Pull request merged**
