### PR TITLE
UnxUtils: Add version 2007.03.01

### LINKED ISSUE #3288: [Request] UnxUtils
https://sourceforge.net/projects/unxutils/files/unxutils/current/UnxUtils.zip/download

the .exe files are located on usr\local\wbin\ inside the zip file

### PR DESCRIPTION
**Pull request by niheaven**
close #3288

### CODE REVIEW

**Comment by h404bi** [comment]
You may submit it to https://github.com/scoopinstaller/scoop-main

**Comment by niheaven** [comment]
Only submit there or both?

**Comment by h404bi** [comment]
Both, the commits of the main bucket has been extracted and frozen here. `scoopinstaller/scoop-main` will not contain any commits after https://github.com/lukesampson/scoop/commit/9eed3d8914c7a0fa294110eb0761776a01adf034.

**Comment by niheaven** [comment]
Okay, I'll move all my unmerged main bucket PR there.

**Pull request closed without merging**
