### PR TITLE
Add debugview++

### PR DESCRIPTION
**Pull request by amaechler**
This PR adds an app manifest for [`debugview++`](https://github.com/CobaltFusion/DebugViewPP).

- Releases from GitHub
- Binaries: `DebugView++.exe`

### CODE REVIEW

**Comment by r15ch13** [comment]
Since this is a GUI I would suggest adding it to the [extras bucket](https://github.com/lukesampson/scoop-extras).

* Add 64/32 bit version
* Add note about OutputForwarderVSIX
* Add shortcut
* Add DebugViewConsole.exe to `bin` and create `DebugView` alias

```json
{
    "homepage": "https://github.com/CobaltFusion/DebugViewPP",
    "description": "DebugView++, collect, view and filter your application logs",
    "license": "BSL-1.0",
    "version": "1.8.0.34",
    "architecture": {
        "64bit": {
            "url": "https://github.com/CobaltFusion/DebugViewPP/releases/download/v1.8.0.34/DebugView++.zip",
            "hash": "677389538cd593e10b79c12c113cbda4038a9ca1ea205454c30ebd64d815072d"
        },
        "32bit": {
            "url": "https://github.com/CobaltFusion/DebugViewPP/releases/download/v1.8.0.34-x64/DebugView++.zip",
            "hash": "ff1078c4dc5fb7d9b73cf2edca28e511758980720b4e01aa5fbe23df7c88c14d"
        }
    },
    "bin": [
        "DebugView++.exe",
        [
            "DebugView++.exe",
            "DebugView"
        ],
        "DebugViewConsole.exe"
    ],
    "checkver": "github",
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/CobaltFusion/DebugViewPP/releases/download/v$version/DebugView++.zip"
            },
            "32bit": {
                "url": "https://github.com/CobaltFusion/DebugViewPP/releases/download/v$version-x64/DebugView++.zip"
            }
        }
    },
    "notes": "The 'OutputForwarderVSIX.vsix' is located at '$dir'."
}
```

**Comment by amaechler** [comment]
@r15ch13 Thanks for getting back to me. Good suggestions, I completely missed the 64bit versions.

I can close this PR and open one in the extras repository. I wasn't aware that the main bucket should only contain non-UI executables. Would it make sense to update the [criteria](https://github.com/lukesampson/scoop/wiki/Criteria-for-including-apps-in-the-main-bucket) on the wiki to clarify that point?

**Comment by r15ch13** [comment]
> I can close this PR and open one in the extras repository.

Yes, please :smile:
> Would it make sense to update the criteria on the wiki to clarify that point?

Definitely :+1:

**Comment by amaechler** [comment]
Moved to lukesampson/scoop-extras#1343.

**Pull request closed without merging**
