### PR TITLE
Updated Bazel to 0.25.0.

### PR DESCRIPTION
**Pull request by excitoon**
@lukesampson @r15ch13 Pls merge this.

### CODE REVIEW

**Comment by r15ch13** [comment]
Please use the new [main bucket](https://github.com/scoopinstaller/scoop-main)
It was already updated to version 0.25.0
https://github.com/scoopinstaller/scoop-main/blob/master/bucket/bazel.json

**Comment by excitoon** [comment]
Oh thank you.

**Comment by excitoon** [comment]
I wonder why you did not use `git filter-branch` in order to preserve history.

**Comment by r15ch13** [comment]
The history was preserved, but GitHub doesn't show it.
See commit history: https://github.com/scoopinstaller/scoop-main/commits/master?after=b46606d7ba08f52eb27a5775f6d83115e640894d+174
`Init scoop-main bucket` was committed 11 days ago. :smile:

**Pull request closed without merging**
