### PR TITLE
Add Ammonite Scala REPL

### PR DESCRIPTION
**Pull request by nightscape**

### CODE REVIEW

**Comment by rasa** [comment]
The URL https://github.com/lihaoyi/Ammonite/releases/download/1.1.2/2.12-1.1.2#/amm.bat is a .jar file. Why give it a .bat suffix?

**Comment by nightscape** [comment]
It's a tweaked JAR file that contains some lines of script to allow it to be used as `.bat` file.
See the docs: http://ammonite.io/#UnstableVersions

**Comment by rasa** [comment]
You're right. I tested it and it works!

**Comment by nightscape** [comment]
Yeah, actually quite a nice technique. It even seems to work across shells 😄

**Pull request merged**
