### PR TITLE
Fix license attributes to SPDX standard

### PR DESCRIPTION
**Pull request by rasa**

### CODE REVIEW

**Comment by r15ch13** [comment]
What about adding `license_url` or changing it to an object?

```json
"license": {
    "identifier": "MIT|Apache-2.0",
    "url": "https://example.org"
}
```

**Comment by rasa** [comment]
Agreed. Can we do that in a follow up PR?

**Comment by r15ch13** [comment]
Why not update this one?

Here is a schema proposal:
```json
        "license": {
            "anyOf": [
                {
                    "type": "string"
                },
                {
                    "additionalProperties": false,
                    "properties": {
                        "url": {
                            "format": "uri",
                            "type": "string"
                        },
                        "identifier": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "identifier"
                    ],
                    "type": "object"
                }
            ]
        },
```

**Comment by rasa** [comment]
Sounds good. I’ll add this schema change to this PR.

**Comment by rasa** [comment]
Gonna start a new PR.

**Pull request closed without merging**
