### PR TITLE
Create shims for bash scripts

### PR DESCRIPTION
**Pull request by r15ch13**
Potential fix to help Cygwin/MinGW users.
Related issues: #1436, #894, https://github.com/lukesampson/scoop-extras/issues/434

### CODE REVIEW

**Comment by lukesampson** [comment]
I'm not sure if I'm following the code logic — does this only create a bash shim if the target to be shimmed doesn't have an extension of `exe`, `bat`, `cmd`, or `ps1`?

So if a manifest has `"bin": "code.cmd"`, a bash shim wouldn't be created, but if it has `"bin": "code.xyz"` it would?

**Comment by r15ch13** [comment]
Basically yes. All bash script have no extension, but I can add a check for the [Shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)) so it will not create useless shims.

**Comment by lukesampson** [comment]
Okay sounds good. I was thinking it would try to shim every `bin` for bash, but I guess that's a lot harder to do.

**Comment by lukesampson** [comment]
I think you also need to avoid writing the .ps1 shim ([lines 181 - 190](https://github.com/lukesampson/scoop/blob/02730deed3ccf986de6ca51dbd100ecff88fd88f/lib/core.ps1#L181-L190)) if you're shimming a bash script, otherwise it will create a .ps1 shim that won't execute, and it would overwrite the correct .ps1 shim in the case of `"bin": [ "bin/code.cmd", "bin/code" ].

**Comment by nrakochy** [comment]
If I understand this correctly, this pr would allow the executables to be picked up by `Cygwin`? Would be a great help for me.

**Comment by Ash258** [comment]
@r15ch13 #2741?

**Comment by rasa** [comment]
This issue appears obsolete. If not, please reopen.

**Pull request closed without merging**
