### PR TITLE
Add reverse property to checkver

### PR DESCRIPTION
**Pull request by r15ch13**
Add a reverse property to checkver.
If set to true, the regex matches get reversed.
This helps to find new versions in directory listings. (see x264)

Like: https://download.videolan.org/pub/x264/binaries/win64/

I know there are other programs with the same problem, but I can't remember them right now :grin:

**Needs testing on Unix!**

### CODE REVIEW

**Comment by matthewjberger** [comment]
What is the status of this? I have some manifests I'd like to do where this would be useful and I'm looking forward to this pull request being merged. Excellent idea!

**Comment by r15ch13** [comment]
Tested on unix

**Comment by r15ch13** [comment]
@matthewjberger

**Comment by matthewjberger** [comment]
Thank you!

**Pull request merged**
