### PR TITLE
Add apimtemplate (0.1-alpha)

### PR DESCRIPTION
**Pull request by MichielVanwelsenaere**
handy tool when working with Microsoft Azure APIM.

### CODE REVIEW

**Comment by niheaven** [comment]
Please submit manifest related PR in https://github.com/scoopinstaller/scoop-main, see https://github.com/scoopinstaller/scoop-main/pull/3 for reference.

**Comment by MichielVanwelsenaere** [comment]
Ok, so there seems to be a migration for scoop to another repo.
Some questions/remarks:
- what's the general idea?
- how should we migrate an existing setup to use the new repo?
- a note on the migration on this repo would be nice
- does the migrated bucket keeps using the extras bucket from this repo?

**Comment by niheaven** [comment]
Please see https://github.com/lukesampson/scoop/pull/3060 as reference.

You can use `develop` branch of scoop-core (this repo) to use the main bucket, and you can use `develop` as follow (before https://github.com/lukesampson/scoop/pull/3372 is merged)

1. Go to scoop dir (`$SCOOP\apps\scoop\current`)
1. `git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"`
1. `git fetch --force origin -q`
1. `git checkout -B develop -t origin/develop -q`
1. `git reset --hard origin/develop -q`
1. `scoop update`

This will switch to 'develop' channel of scoop, and add 'main' bucket for you. If met some error, please submit a PR about it.

Except for the extracted 'main' bucket, everything is the same as before, include other buckets.

**Comment by Ash258** [comment]
For normal users everything will remain same. Except main manifests (git, 7z, ...) will be in other repo. But normal user will not notice change. You just run `scoop update` and everything will be done automatically.

**Comment by MichielVanwelsenaere** [comment]
so you're using this branch as you dev and the other repo as edge, ok thanks!

**Comment by iainsgillis** [comment]
Cool -- thanks! I'll read up on my lunch break.

**Pull request closed without merging**
