### PR TITLE
Add bucket and arch to list/export output

### PR DESCRIPTION
**Pull request by rasa**
Transforms `scoop list` from:
````
  netcat (1.12)
  notepadplusplus (7.4.2)
  openssl10x (1.0.2L)
  pciutils (3.5.5)
````
to:
````
  netcat (1.12)
  notepadplusplus (7.4.2) [extras] {32bit}
  openssl10x (1.0.2L) [versions]
  pciutils (3.5.5) {32bit}
````
I originally changed it to
````
  netcat (1.12)
  extras/notepadplusplus (7.4.2) {32bit}
  versions/openssl10x (1.0.2L)
  pciutils (3.5.5) {32bit}
````
but it didn't feel alphabetical any more.

### CODE REVIEW

**Comment by rasa** [comment]
Given that neither an app name, nor the version can have spaces in them, why not simply show:
````
netcat 1.12
notepadplusplus 7.4.2 (32bit) [extras]
openssl10x 1.0.2L [versions]
pciutils 3.5.5 (32bit)
````

**Comment by inosik** [comment]
:+1: for showing the bucket/url.

Sometimes I install apps from my local clone/before a PR to a bucket gets merged, and then wonder why an app doesn't get updated.

**Comment by rasa** [comment]
@inosik I've been tripped up by that too! Now, you'll see the file/URL of each package, if it wasn't installed from a bucket. For example:
````
openssl10x 1.0.2L [C:\Users\you\bucket\openssl10x.json]
````

**Comment by rasa** [comment]
@lukesampson: Any feedback on this PR? Or would you prefer:
````
netcat 1.12
notepadplusplus 7.4.2 (32bit) [extras]
openssl10x 1.0.2L [versions]
pciutils 3.5.5 (32bit)
````
as neither app name, nor versions can have spaces in them, so the parens are superfluous.

**Pull request merged**
