### PR TITLE
Persist cache

### PR DESCRIPTION
**Pull request by nueko**

### CODE REVIEW

**Comment by r15ch13** [comment]
This is more clear: `"post_install": "yarn config set cache \"$persist_dir\\cache\"",`

The note will not work if `npm` isn't installed. Also `yarn` adds global binaries to `%APPDATA%\Local\Yarn\bin`.

**Comment by nueko** [comment]
> %LOCALAPPDATA%\Yarn\bin to the PATH might be a better idea. 

Agree!

> The note will not work if npm isn't installed. Also yarn adds global binaries to %LOCALAPPDATA%\Yarn\bin.

That's why it just a note, yarn global bin will set to the npm global bin if we set the prefix to yarn config

**Comment by r15ch13** [comment]
If we add the global bin to PATH, then we don't need the note.

**Comment by nueko** [comment]
Can You tweak it, mate? I have to _sahur_ right now.

**Comment by r15ch13** [comment]
Yep

**Comment by r15ch13** [comment]
In which way would this be better? I think it is more confusing.

**Comment by nueko** [comment]
Ah, nevermind.
That's user choice.
I think that's enough

**Pull request merged**
