### PR TITLE
Startmenu Shortcut Support 

### PR DESCRIPTION
**Pull request by damnhandy**
PR for issue #678

### CODE REVIEW

**Comment by lukesampson** [comment]
This looks cool. What do you think about grouping the shortcuts under a start menu folder? Maybe called "Apps" or something generic. Just so we don't overwrite the user's other shortcuts accidentally.

Also can you check over the code style for `createShortcut` so it matches the other code? Lower-case, underscored names etc. Everything else looks good.

**Comment by damnhandy** [comment]
Yeah, I was wondering about something like that myself. I was thinking something more specific to Scoop like `Scoop Apps` for `Scoop Applications`. Reason being I know a few places that group corporate apps under a Start menu folder called `Apps`. Grouping them under a single folder would make more sense.

**Comment by lukesampson** [comment]
Cool, let's try it out!

**Comment by Stanzilla** [comment]
@lukesampson Any reason why not put the shortcuts into the start menu directly instead of using the `Scoop apps` folder? Would make them feel more "native" if you know what I mean, taking scoop out of the shortcut making them feel like they were installed "normally".

**Comment by rasa** [comment]
Or maybe set the folder name as a config option:
```
scoop config startmenu_folder “Scoop Apps”
```
and default to “” for new installs?

**Comment by lukesampson** [comment]
Yes, that might be nicer installing directly to the start menu by default but making it configurable.

**Comment by rasa** [comment]
This would address the Windows 10 issue in https://github.com/lukesampson/scoop/issues/2124

**Pull request merged**
