### PR TITLE
add hashcat and just hashcat

### PR DESCRIPTION
**Pull request by 7anner**

### CODE REVIEW

**Comment by r15ch13** [comment]
Add `"extract_dir": "hashcat-3.5.0"` and `"extract_dir": "hashcat-$version"` to hashcat. Then remove `hashcat-3.5.0\` from every `bin` option. Because `bin` can't use `$version` substitions. Easy way to test if everything works. Change the `version` to `3.4.0` and run `.\bin\checkver.ps1 hashcat -u` in your repo.

**Comment by r15ch13** [comment]
protobuf is already available in the [extras bucket](https://github.com/lukesampson/scoop-extras/blob/master/protobuf.json)

**Comment by 7anner** [comment]
okay, shoot.  What do I need to do to appease appveyor?

**Comment by r15ch13** [comment]
You can remove the `architecture` completely from `autoupdate` :smile:

**Pull request merged**
