### PR TITLE
Add digdag (distributed workflow tool)

### PR DESCRIPTION
**Pull request by klauern**
Digdag is a distributed workflow tool, pointed out in the "assess" branch of Languages and Frameworks on Thoughtworks 2017 radar: https://www.thoughtworks.com/radar/languages-and-frameworks

### CODE REVIEW

**Comment by rasa** [comment]
@klauern Can you add a return to the end of the last line, to make our CI happy?

**Comment by klauern** [comment]
fixed.  I also noticed that it wasn't even in the right path....

**Comment by rasa** [comment]
Sorry, but the CI now says: The following files have utf-8 BOM. Can you fix?

**Comment by klauern** [comment]
Sorry about that.  You'd think that editing it with VSCode (and the editorconfig extension installed/enabled) would have fixed these by default for me.  OH well.  In any event, I think things are working.

**Pull request merged**
