### PR TITLE
Add gifsicle 1.89

### PR DESCRIPTION
**Pull request by deevus**
I haven't added anything for a while so I wanted to do it the official way to make sure everything is all good with this one :)

### CODE REVIEW

**Comment by deevus** [comment]
Doesn't look like autoupdate is a possibility for this one. The Windows port has release zips only and isn't up to date with the source github

**Comment by rasa** [comment]
There's https://github.com/rasa/scoops/blob/master/gifsicle.json

I wonder if anything else is worthy of moving to the main bucket, or extras?

**Comment by rasa** [comment]
@deevus Absolutely. I was just suggesting we consider moving other packages in https://github.com/rasa/scoops to the main bucket or extras. Sorry I wasn’t more clear.

**Comment by deevus** [comment]
I'll leave it to you to go through your bucket to see what can be brought over :+1:

**Pull request merged**
