### PR TITLE
Do not use proxy if set to none

### PR DESCRIPTION
**Pull request by gitolicious**

### CODE REVIEW

**Comment by r15ch13** [comment]
Related to https://github.com/lukesampson/scoop/issues/1728?

**Comment by gitolicious** [comment]
Indeed... I missed that one!
After some further investigation, git also doesn't work with the currentuser@default trick. Need to dig deeper and will get back to you.

**Comment by r15ch13** [comment]
`lib\config.ps1` is already loaded when `lib\git.ps1` is used, so `[net.webrequest]::defaultwebproxy` should return the correct address + credentials I guess.
Does something like this work? `$proxy = [net.webrequest]::defaultwebproxy`

I don't know and use any proxy, so I can't test it.

**Comment by h404bi** [comment]
@r15ch13 @rasa close this, it's already implemented.

**Pull request closed without merging**
