### PR TITLE
Add unbound

### PR DESCRIPTION
**Pull request by nueko**

### CODE REVIEW

**Comment by lukesampson** [comment]
`post_install` is not an appropriate place for starting services.

**Comment by r15ch13** [comment]
https is available for all URLs

**Comment by nueko** [comment]
@lukesampson the `post_install` just replace a string on an extracted file.
@r15ch13 will update it.

**Comment by lukesampson** [comment]
Sorry, I meant `pre_install` — what's that doing?

**Comment by nueko** [comment]
it is just proxing `unbound` command without parameter to provide right default configuration, 
user should run `unbound -c ~/scoop/apps/unbound/current/service.conf` to run unbound
but with the `pre_install` i created, just  `unbound` is enough. also it runs in bg as it should.
is that too much?

**Comment by lukesampson** [comment]
Thanks for explaining. I'm a bit slow — I thought it was running that command rather than writing it to a file. It is a more code than is ideal, but it's okay in the absence of a `scoop service` command.

**Pull request merged**
