### PR TITLE
whitespace cleanup

### PR DESCRIPTION
**Pull request by rivy**
This PR updates the repository to the current `.editorconfig` specifications.

Additionally, I've created a BAT/CMD script to test for files which don't meet repository criteria (see https://gist.github.com/rivy/363672794368da2e810f). The script tests using `pcregrep` which can be obtained from http://pcre.org (Windows binary @ http://www.rexegg.com/pcregrep-pcretest.html).

I think it would be a good idea to incorporate these five tests into the Appveyor tests. Unfortunately, I don't know "pester" at all, so, I haven't had the time to learn it and generate the appropriate tests.

### CODE REVIEW

**Comment by rivy** [comment]
The whitespace cleanup commit avoids fully "fixing" all of the test files. I wasn't sure if all of the testing text files could be changed without bollixing up the tests. And, unfortunately, my Appveyor testing queue is stuck, so I couldn't test it.

Once I get it "unstuck", I'll try to fix all of the test files and submit another commit if it passes tests.

**Comment by deevus** [comment]
Great work on this. Thanks

**Comment by rivy** [comment]
Appveyor is finally back in operation for me.

So, I've now successfully changed and tested all the test fixture files. The entire repo is compliant now without any test errors.

I've also updated the repo test script (https://gist.github.com/rivy/363672794368da2e810f) to test all source files. And it's reporting no issues over the whole repo.

**Comment by deevus** [comment]
Perhaps we should get `pcregrep` into the main bucket. 

How do you propose enforcing this for new manifests?

**Comment by deevus** [comment]
Sorry I missed the part where you mentioned incorporating this into the Pester tests.

**Comment by rivy** [comment]
I'd be happy to incorporate tests... The gist mentioned above does have the regular expressions needed to test all the files. But I don't know the mechanics of testing with "pester". If someone could give me a few pointers, I'd be happy to incorporate them into the tests.

As for `pcregrep`, I've mirrored the PCRE SVN repo on github (@rivy/PCRE2). I've got it compiling, but there are several compilation options that I don't understand yet. So I'm not sure how to produce the best windows version. When I get it compiling in best form, I'll produce a release and PR to incorporate it.

There is a `pcregrep` binary available (as noted previously), but it's on a private site and the producer isn't saying how it's compiled.

**Comment by rivy** [comment]
I created a repo for PCRE (https://github.com/rivy/PCRE) that contains instructions and source for building PCRE under Windows.




Using it, I’ve got the most recent release compiled and repackaged for Windows (https://github.com/rivy/PCRE/releases/latest).




I also added the package to my scoop-bucket (https://github.com/rivy/scoop-bucket/blob/master/pcregrep.json). And, I’d be happy to make a PR for it, but I’m unsure whether you’d prefer adding it to the main scoop bucket or the extras.




- Roy






From: Simon Hartcher
Sent: ‎Wednesday‎, ‎August‎ ‎19‎, ‎2015 ‎7‎:‎30‎ ‎PM
To: lukesampson/scoop
Cc: Roy Ivy III





Perhaps we should get pcregrep into the main bucket. 

How do you propose enforcing this for new manifests?

**Comment by rivy** [comment]
@deevus , I wanted to check in on this...

I've got a more substantial set of patches that adds improved functionality from the CMD shell. It updates the CMD shell environmental after scoop commands, avoiding the onerous requirement of restarting the shell to finish the install process (feature parity with PowerShell). It also fixes a couple of more subtle problems with the update process.

I've been using it successfully for the last couple of weeks.

Point being that it's difficult to base the patches on the current master without clouding the important code changes with swaths of lines having only whitespace changes.

**Comment by deevus** [comment]
I think what needs to happen is: 
- Get PCRE in scoop 
- Integrate PCRE into testing via this PR
- Merge it in

I see that you have been creating some new tests using Pester, so do you think you're more confident to integrate the tests for this now?

**Comment by deevus** [comment]
In regards to https://github.com/rivy/scoop/commit/57f0571 

Can you explain in a bit more detail what is going on? This can just be a part of the PR when you get to it.

**Comment by deevus** [comment]
If you think it meets the criteria in #451 lets get it in the main bucket

**Comment by rivy** [comment]
PCRE isn't needed for testing. The last set of commits (starting with 6545f2e) added all of the same tests into the pester testing set. All of the whitespace style rules run automatically upon checkin with the PR in this current shape. So, if you're comfortable with this as a PR, the current version is complete.

I'll look into the PCRE issue separately in a bit, but, again, it's unnecessary for this PR.

As an aside, the commit  rivy@57f0571 is just a working preview. I'm going to be posting (and solving) three issues over the next day or so, in order to explain each step in the process. Unfortunately, anytime you try to get anything significant done with BAT/CMD scripts, it always involves a lot more code effort and complexity to get it correct.

**Comment by deevus** [comment]
@rivy Great work. If you can just resolve the conflicts I'll merge it in

**Comment by rivy** [comment]
Done.

**Comment by deevus** [comment]
:+1:

**Pull request merged**
