### PR TITLE
load proxy from env for aria2

### PR DESCRIPTION
**Pull request by Cologler**
load `$env:HTTPS_PROXY` and `$env:HTTP_PROXY` and pass to aria2

### CODE REVIEW

**Comment by Cologler** [comment]
I have no idea how to write unit test for proxy, but this works on my PC.

**Comment by h404bi** [comment]
Please change branch to develop branch.

**Comment by Cologler** [comment]
move to #3521

**Comment by Ash258** [comment]
What @h404bi  meant was to change base branch of this PR to develop.

**Comment by Cologler** [comment]
move to #3522

**Pull request closed without merging**
