### PR TITLE
fix(versions): Refactor `compare_versions` -> `Compare-Version`

### LINKED ISSUE #2720: scoop update does not update to manifest version
```
PS C:> scoop update openssl
openssl: 1.1.1_8 (latest version)
Latest versions for all apps are installed! For more information try 'scoop status'
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.

PS C:> scoop info openssl
Name: openssl
Version: 1.1.1_8 (Update to 1.1.1 available)
Website: https://curl.haxx.se/windows/
License: OpenSSL (https://spdx.org/licenses/OpenSSL.html)
Manifest:
  ~\scoop\apps\scoop\current\bucket\openssl.json
Installed:
  ~\scoop\apps\openssl\1.1.1_8
Binaries:
   openssl.exe
Environment:
  OPENSSL_CONF=~\scoop\apps\openssl\current\openssl.cnf
  PATH=%PATH%;~\scoop\apps\openssl\1.1.1_8
```

### LINKED ISSUE #2981: Package not recognised by scoop as outdated (adopt11-hotspot)
Running `scoop info adopt11-hotspot` gives the version as:
```
...
Version: 11-28 (Update to 11.0.1-13 available)
...
```
But running `scoop update *` gives:
```
Latest versions for all apps are installed! For more information try 'scoop status'
```
And specifically running `scoop update adopt11-hotspot` gives
```
adopt11-hotspot: 11-28 (latest version)
Latest versions for all apps are installed! For more information try 'scoop status'
```

I haven't tried uninstalling/reinstalling yet since if that fixed it the actual cause of the bug would presumably be a lot harder to identify.

### LINKED ISSUE #3329: scoop does not detect new java versions
```
PS C:> scoop update oraclejdk
Latest versions for all apps are installed! For more information try 'scoop status'
[..]
PS C:> scoop update -f oraclejdk
oraclejdk: 12-33 -> 12.0.1-12 (global)
Updating one outdated app:
[..]
Updating 'oraclejdk' (12-33 -> 12.0.1-12)
Downloading new version
Starting download with aria2 ...
[..]
```

Ref: https://gitter.im/lukesampson/scoop?at=5ca87f711f6e900d5ee9881f

### PR DESCRIPTION
**Pull request by niheaven**
fix #3329, fix #2981, fix #2720, fix https://github.com/lukesampson/scoop-extras/issues/2106

Now force updating to manifest's version, despite installed version is greater or less than it.

### CODE REVIEW

**Comment by r15ch13** [comment]
More tests:

```powershell
describe "versions" -Tag 'Scoop' {
    it 'compares versions with integer-string mismatch' {
        compare_versions '1.8.9' '1.8.5-1' | should -be 1
    }

    it 'handles plain string version comparison to int version' {
        compare_versions 'latest' '20150405' | should -be 1
    }

    it 'handles dashed version components' {
        compare_versions '7.0.4-9' '7.0.4-10' | should -be -1
        compare_versions '7.0.4' '7.0.4-9' | should -be -1
        compare_versions '7.0.4-9' '7.0.4-10' | should -be -1
    }

    it 'handle example comparisons' {
        compare_versions '1' '1.1' | should -be -1
        compare_versions '1.0' '1.1' | should -be -1
        compare_versions '1.1' '1.0' | should -be 1
        compare_versions '1.1' '1' | should -be 1
        compare_versions '1.1.1_8' '1.1.1' | should -be 1
        compare_versions '1.1.1b' '1.1.1a' | should -be 1
        compare_versions '1.1.1a' '1.1.1b' | should -be -1
        compare_versions '2019-01-01' '2019-01-02' | should -be -1
        compare_versions '2019-01-02' '2019-01-01' | should -be 1
        compare_versions '2018-01-01' '2019-01-01' | should -be -1
        compare_versions '2019-01-01' '2018-01-01' | should -be 1
    }

    it 'handles comparsion against en empty string' {
        compare_versions '7.0.4-9' '' | should -be 1
    }

    it 'handles equal versions' {
        compare_versions '12.0' '12.0' | should -be 0
        compare_versions '7.0.4-9' '7.0.4-9' | should -be 0
    }
}
```

By checking if `$a` and `$b` are equal at the top of `compare_versions` we can skip the comparison stuff.
```powershell
    if($a -eq $b) {
        return 0
    }
```

**Comment by r15ch13** [comment]
Related issue: https://github.com/lukesampson/scoop-extras/issues/2106

Maybe we could remove the version comparison entirely like @se35710 [mentioned](https://github.com/lukesampson/scoop/issues/3329#issuecomment-484569743).
If the installed version isn't the same as the from the Manifest then it's outdated.

Comparing versions that don't follow a schema like semver.org is pretty much useless anyway. But there are more normal versions then odd ones. See below (includes Main/Extras/Versions and outdated Java/PHP/NerdFonts buckets):

Normal version numbers:
```powershell
X:\~projects\~powershell
λ (Get-ChildItem *\bucket\*.json -Recurse | % { (Get-Content $_ | ConvertFrom-Json).version } | ? { $_ -match "^[\d.]+$" }).Count
1181
```

Odd versions with other symbols then `0-9` and `.`
```powershell
X:\~projects\~powershell
λ (Get-ChildItem *\bucket\*.json -Recurse | % { (Get-Content $_ | ConvertFrom-Json).version } | ? { $_ -notmatch "^[\d.]+$" }).Count
224
```

**Comment by niheaven** [comment]
@r15ch13 Please consider merge this PR, `mupdf` update from `1.16.0-rc2` to `1.16.0` but scoop cannot update it excepts with `-f`...

**Comment by xfournet** [comment]
Could you add the following test ? (see https://github.com/Ash258/Scoop-JetBrains/issues/11)

```
    it 'handles unbalanced versions' {
        Compare_Versions '2019.2.1-192.6262.58' '2019.2-192.5728.98' | Should -Be 1
    }
```

**Pull request merged**
