### PR TITLE
update latex url

### PR DESCRIPTION
**Pull request by gheoan**
The current url results in error:
```shell
Cannot handle redirect from HTTP/HTTPS protocols to other dissimilar ones.
URL http://mirrors.ctan.org/systems/win32/miktex/setup/miktex-portable-2.9.6361.exe#/dl.7z is not valid
````

### CODE REVIEW

**Comment by r15ch13** [comment]
This happens because `mirrors.ctan.org` redirects to FTP mirrors...
Did you try it again, maybe it returns an HTTP/HTTPS mirror.

**Comment by r15ch13** [comment]
Changed it to the only HTTPS mirror that's available.

**Comment by gheoan** [comment]
I get 404 error on `https://ftp.uni-erlangen.de/systems/win32/miktex/setup/miktex-portable-2.9.6361.exe`. I wonder if it is region locked.

**Comment by r15ch13** [comment]
Nah, fucked up the URL.
Should have been https://ftp.uni-erlangen.de/ctan/systems/win32/miktex/setup/miktex-portable-2.9.6361.exe

**Comment by r15ch13** [comment]
Fixed with https://github.com/lukesampson/scoop/commit/9a5450eb34d6952438653f32af9d38cd42c6c034

**Pull request merged**
