### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by nueko**
Set Composer home and register composer global bin

### CODE REVIEW

**Comment by r15ch13** [comment]
Composer uses `%APPDATA%\Composer` to store it's data. What's the use case for setting `COMPOSER_HOME`?

**Comment by nueko** [comment]
multi user purpose when scoop directory not inside the `%USERPORFILE%`

**Comment by r15ch13** [comment]
Also requires less space, because all use the same `vendor` directory. I see.
But `persist` can't be empty. So let's add a `home` directory, make it persistent and point the `COMPOSER_HOME` to it. The `bin` path points to the linked `~\scoop\composer\current\home` directory.
Should look like this:
```
    "persist": [
        "home"
    ],
    "env_set": {
        "COMPOSER_HOME": "$persist_dir\\home"
    },
    "env_add_path": "home\\vendor\\bin",
```

**Comment by nueko** [comment]
also, should we move %APPDATA%\Composer to the new one?

**Comment by r15ch13** [comment]
Yeah, I agree. At least until the next composer update.

**Comment by nueko** [comment]
I think, we should just throw warning about `COMPOSER_HOME` variable creation and recommend user to move it to the new location.
Or it is better to write an `postinstall` script?

**Comment by r15ch13** [comment]
A `postinstall` script and a warning only when something was moved should be okay.

**Pull request merged**
