### PR TITLE
Installing specific versions using autoupdate feature

### LINKED ISSUE #538: Install specific version
Hi,

I ran `scoop install rsync` which install version 3.1.1. On my servers running under Debian stable, I have rsync 3.0.9 (latest available there) which has a compatibility issue with 3.1.1. 

How can I install 3.0.9 on my local computer ? Is there something like `scoop install rsync@3.0.9`?

### PR DESCRIPTION
**Pull request by deevus**
- Fixes #538

TODO:

- [x] resetting between specifically installed versions
- [x] support installing of multiple specific versions of the same app
- [ ] quieting autoupdate output

### CODE REVIEW

**Comment by deevus** [comment]
I've been plugging away at this for a few hours and I wanted to get some feedback. 

If you run `scoop install yarn@0.20.0` the following happens:

- scoop-install identifies the specific version syntax
- a user manifest is generated at `$env:scoop/usermanifests` (this can be changed)
- the specific version is replaced with the path to the manifest and installation continues as normal

**Comment by deevus** [comment]
There's things that need to be resolved such as:

- resetting between specifically installed versions
- quieting autoupdate output
- support installing of multiple specific versions of the same app

**Comment by deevus** [comment]
Installing/resetting specific versions

```
scoop install-specific-version $ = $ bin/scoop install hub@2.2.8
Given version (2.2.8) does not match manifest (2.2.9)
Attempting to generate manifest for 'hub' (2.2.8)
Autoupdating hub
Unable to check github/nuget/chocolatey/bitbucket url (assuming it is ok)
Download files to compute hashes!
hub-windows-386-2.2.8.zip (3.0 MB) [=====================================================================================================================================================================] 100%
Unable to check github/nuget/chocolatey/bitbucket url (assuming it is ok)
Download files to compute hashes!
hub-windows-amd64-2.2.8.zip (3.3 MB) [===================================================================================================================================================================] 100%
Writing updated hub manifest
Installing 'hub' (2.2.8).
Loading hub-windows-amd64-2.2.8.zip from cache
Checking hash of hub-windows-amd64-2.2.8.zip... ok.
Extracting... done.
Linking ~\appdata\local\scoop\apps\hub\current => ~\appdata\local\scoop\apps\hub\2.2.8
Creating shim for 'hub'.
'hub' (2.2.8) was installed successfully!
scoop install-specific-version $ = $ git version
git version 2.12.2.windows.1
hub version 2.2.8
scoop install-specific-version $ = $ bin/scoop reset hub@2.2.9
Resetting hub (2.2.9).
Linking ~\appdata\local\scoop\apps\hub\current => ~\appdata\local\scoop\apps\hub\2.2.9
Creating shim for 'hub'.
scoop install-specific-version $ = $ git version
git version 2.12.2.windows.1
hub version 2.2.9
scoop install-specific-version $ = $ bin/scoop reset hub@latest
Resetting hub (2.3.0-pre9).
Linking ~\appdata\local\scoop\apps\hub\current => ~\appdata\local\scoop\apps\hub\2.3.0-pre9
Creating shim for 'hub'.
```

**Comment by deevus** [comment]
@lukesampson @r15ch13 @rrelmy Apart from autoupdate output (which isn't that important) I think this is done. Can you guys test it and let me know if you find any issues?

**Comment by r15ch13** [comment]
Also i was thinking about extracting older manifest versions with git.

```
> git log --oneline bucket/php.json | grep -i php | grep 7.1.2
> f1693d0 Update php to version 7.1.2
> git show f1693d0:bucket/php.json
```

**Comment by deevus** [comment]
Using git was how I did it originally. The older the manifests the less
likely they'll work. Be it broken urls or other issues. You also can't
install versions that never existed in scoop. With this new solution you
can also go forward, in the case where you want to install some bleeding
version

**Comment by deevus** [comment]
I'd appreciate some help modifying it to work with persist if possible

**Comment by deevus** [comment]
@r15ch13 I fixed that error that you got inside `autoupdate`. If the download(s) fail it should just stop.

**Comment by rrelmy** [comment]
Looks good to me, great work.

I merged the branch with master to resolve the merge conflicts from the persist branch.

**Comment by deevus** [comment]
Lets leave this as a bit of a hidden feature for a while. I'll write some docs for it soon enough

**Pull request merged**
