### PR TITLE
fix(decompress): fix bugs on extract_dir

### PR DESCRIPTION
**Pull request by issaclin32**
This fixes the error when `extract_dir` contains spaces, such as "ISLC v1.0.1.2"
(encountered in: https://github.com/lukesampson/scoop-extras/pull/2398)

Please let me know if there are any problems. Thanks.

### CODE REVIEW

**Comment by Ash258** [comment]
Change base branch to develop

**Comment by r15ch13** [comment]
This would result in `"-ir!C:\bla\bla\"*`, but shouldn't it be `"-ir!C:\bla\bla\*"`?

**Comment by issaclin32** [comment]
> This would result in `"-ir!C:\bla\bla\"*`,
> but shouldn't it be `"-ir!C:\bla\bla\*"` or `-ir!"C:\bla\bla\*"`?

Changing it to `-ir!"C:\bla\bla\*"` now. Thanks for the suggestion.

I thought that would result in taking `*` literally and won't work, but it works just fine.

**Comment by Luckz** [comment]
I'd still really like to install ISLC some day 🥇

**Comment by gothicx** [comment]
Closes #2519

**Pull request merged**
