### PR TITLE
rclone: Add desc and au.hash, persist config, and use download url in main site

### PR DESCRIPTION
**Pull request by niheaven**
- Add `description`
- Use download urls in `downloads.rclone.org` (main site)
- Add `env_set` to persist config in persist_dir of scoop
- Use version file in download site to `checkver`
- Add `autoupdate.hash`

### CODE REVIEW

**Comment by r15ch13** [comment]
The default value `%XDG_CONFIG_HOME%` is `%HOME%\.config` and should be changed to `persist_dir` of rclone for the whole system. This would probably break other Linux based programs too. (See https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html)

**Comment by niheaven** [comment]
Use `$persist_dir\..` to make sure config file is `persist\rclone\rclone.conf` and not `persist\rclone\rclone\rclone.conf`.

But maybe it's better to not set the env var, and let rclone place its config to `%HOME%\.config\rclone`, isn't it?

**Comment by r15ch13** [comment]
Yes, please remove the `env_set` property.

**Comment by niheaven** [comment]
It's okay, and the one in rclone-beta(https://github.com/scoopinstaller/versions/pull/102) is also removed.

**Pull request merged**
