### PR TITLE
set working directory for shortcuts

### PR DESCRIPTION
**Pull request by winteryoung**
@r15ch13 I haven't test this. Do you have a low cost way to test core? I don't have a VM.

### CODE REVIEW

**Comment by matthewjberger** [comment]
If you want a cheap and quick windows VM setup you can do this:

1.) Install VirtualBox
2.) run `scoop install vagrant`
3.) Make a directory named win7 and run the following two commands in it:

```
vagrant init matthewjberger/win7-64-en
vagrant up
```

4.) Then open virtualbox and you'll see your VM running. Select it and it will pop up the gui for the VM

Good luck!

Note:
You can spin up a new vm in this same manner and you'll already have the win7 base ready to go because it only needs to download the first time. Each VM you spin up is a copy of the base so you can safely delete it without destroying the original win7 base box that you downloaded.

**Comment by r15ch13** [comment]
@winteryoung I test everything with my current production system. One year old Win10 installation.
I really should switch to using VMs, but I think they are annoying. (I often fix scoop issues between two rounds of PUBG :D)

**Comment by matthewjberger** [comment]
I agree. They were annoying to me too until I started using vagrant! :)

**Comment by winteryoung** [comment]
I think I will give docker for windows a try. The hyper-v solution seems promising.

**Comment by r15ch13** [comment]
@winteryoung Keep in mind that VirtualBox and VMware Workstation Player will not work anymore when you install Hyper-V.

**Comment by winteryoung** [comment]
@r15ch13 thx. I don't have them installed.

**Comment by winteryoung** [comment]
There's a problem to test core. The [install script](https://raw.githubusercontent.com/lukesampson/scoop/master/bin/install.ps1) is coupled with lukesampson urls. Is there any guidelines to how to test core?

**Comment by winteryoung** [comment]
If there's no guidelines, I will create a new script to install locally.

**Comment by r15ch13** [comment]
Added with https://github.com/lukesampson/scoop/commit/83b823868f5ef5256d3dcfbecff278bb355fefc8

**Pull request closed without merging**
