### PR TITLE
Update Erlang to 18.0

### PR DESCRIPTION
**Pull request by vidarkongsli**

### CODE REVIEW

**Comment by vidarkongsli** [comment]
Is it possible to see an error message about the build failure?

**Comment by deevus** [comment]
@vidarkongsli Not sure why it failed. Can you try rebasing to resolve the merge conflicts?

**Comment by vidarkongsli** [comment]
@deevus Fixed it.

**Comment by deevus** [comment]
@vidarkongsli Looks like you have reverted some changes to other files. You might need to start again if you can't work it out.

**Pull request closed without merging**
