### PR TITLE
Shorter installation command

### PR DESCRIPTION
**Pull request by star2000**
replace
```ps1
iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
```
to
```ps1
iwr -useb get.scoop.sh | iex
```
More elegant, isn't it?

### CODE REVIEW

**Comment by r15ch13** [comment]
Looks nicer but also makes it harder to understand.
I would prefer to add it as a shorter alternative instead of replacing it. 😄 
The current command could be changed to full length with proper casing:
```pwsh
Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
```

**Comment by star2000** [comment]
```ps1
iwr -useb get.scoop.sh | iex
```
full length is
```ps1
Invoke-WebRequest -UseBasicParsing get.scoop.sh | Invoke-Expression
```
`iwr` is abbreviation for `Invoke-WebRequest`,  
`Get-Help Invoke-WebRequest` to see other alias.

**Comment by star2000** [comment]
@r15ch13 merge or close

**Comment by rasa** [comment]
Updated the wiki to match;
https://github.com/lukesampson/scoop/wiki/Quick-Start/_compare/5aa12ee137dadf054c2a8aae62ae20b81396b472...f45fe91d4927ba1fc638cefdbf30e1c044edf5c6

**Comment by rasa** [comment]
This change isn’t in the develop branch.

**Comment by r15ch13** [comment]
It's just the readme. No need to merge it to develop :grin:

**Pull request merged**
