### PR TITLE
Improvements for the reset command to deal with empty `current` alias dir correctly

### PR DESCRIPTION
**Pull request by Retia-Adolf**
#2772 

<del> I think I finally made out this crap... </del>

### CODE REVIEW

**Comment by Ash258** [comment]
What's wrong with reset command, that you need this one?

**Comment by r15ch13** [comment]
I would also suggest adding this feature to the reset command.
Get the last version directory (simply order by modified date) and recreate the `current` directory link.

**Comment by Retia-Adolf** [comment]
@Ash258 well, didn't notice that

ok, it seems lacking of steps of re-linking persist files/dirs; and another problem is:
```
$version = current_version $app $global
```
in the reset command uses function `current_version` in `lib\versions.ps1`, sorts $appdir's version dirs by name. So I should modify it to exclude empty dirs? or... er, as what @r15ch13 suggest? (but why `current` dir would be modified earlier than others, I see what has been reset its `current` is re-linked)



```powershell
scoop list
Installed apps:

  7zip 18.05
  adopt11-hotspot current
  atom current
  bulk-crap-uninstaller current
  cmder current
  concfg current
  cpu-z current
  docker current
  ffmpeg current
  git 2.18.0.windows.1
  gpg4win current
  innounp current
  ipfilter-updater current
  nginx current
  notepadplusplus current
  notepadplusplus-pm current
  nvm current
  peerblock current
  persepolis current
  pester current
  psiphon3 current
  qbittorrent current
  recuva current
  shadowsocks current
  shadowsocksr-csharp current
  tor-browser current
  vagrant current
  win-portacle current
  xdman current
  xx-net current
  zeronet current

PS > scoop reset
ERROR <app> missing
Usage: scoop reset <app>
PS > scoop reset *
Resetting 7zip (18.05).
Linking ~\scoop\apps\7zip\current => ~\scoop\apps\7zip\18.05
Creating shim for '7z'.
Creating shortcut for 7-Zip (7zFM.exe)
ERROR 'adopt11-hotspot (current)' isn't installed
ERROR 'atom (current)' isn't installed
ERROR 'bulk-crap-uninstaller (current)' isn't installed
ERROR 'cmder (current)' isn't installed
ERROR 'concfg (current)' isn't installed
ERROR 'cpu-z (current)' isn't installed
ERROR 'docker (current)' isn't installed
ERROR 'ffmpeg (current)' isn't installed
Resetting git (2.18.0.windows.1).
Linking ~\scoop\apps\git\current => ~\scoop\apps\git\2.18.0.windows.1
Creating shim for 'git'.
Creating shim for 'gitk'.
Creating shim for 'git-gui'.
Creating shim for 'tig'.
Creating shim for 'git-bash'.
Creating shortcut for Git Bash (git-bash.exe)
ERROR 'gpg4win (current)' isn't installed
ERROR 'innounp (current)' isn't installed
ERROR 'ipfilter-updater (current)' isn't installed
ERROR 'nginx (current)' isn't installed
ERROR 'notepadplusplus (current)' isn't installed
ERROR 'notepadplusplus-pm (current)' isn't installed
ERROR 'nvm (current)' isn't installed
ERROR 'peerblock (current)' isn't installed
ERROR 'persepolis (current)' isn't installed
ERROR 'pester (current)' isn't installed
ERROR 'psiphon3 (current)' isn't installed
ERROR 'qbittorrent (current)' isn't installed
ERROR 'recuva (current)' isn't installed
ERROR 'shadowsocks (current)' isn't installed
ERROR 'shadowsocksr-csharp (current)' isn't installed
ERROR 'tor-browser (current)' isn't installed
ERROR 'vagrant (current)' isn't installed
ERROR 'win-portacle (current)' isn't installed
ERROR 'xdman (current)' isn't installed
ERROR 'xx-net (current)' isn't installed
ERROR 'zeronet (current)' isn't installed
```

**Comment by r15ch13** [comment]
Ah, ignore my comment. Didn't think this through.
`current_version` returns the correct version. No need to order the version directories. :smile:

**Pull request merged**
