### PR TITLE
add prometheus

### PR DESCRIPTION
**Pull request by martinlindhe**
This is my first bucket with autoupdate, could someone take a look at so i didn't mess it up?

Also, this is the current **stable** release of prometheus. 2.0 will be released soonish.

### CODE REVIEW

**Comment by r15ch13** [comment]
You can run `.\bin\checkver.ps1 -u -f prometheus` to check if it works.

**Comment by martinlindhe** [comment]
Looking at it, seems I made some mistakes. Updated pr coming shortly.

**Comment by martinlindhe** [comment]
Fixed autoupdate now returns
```
>  .\bin\checkver.ps1 -u -f prometheus
prometheus: 1.7.1 (scoop version is 1.7.1)
Forcing autoupdate!
Autoupdating prometheus
https://github.com/prometheus/prometheus/releases/download/v1.7.1/sha256sums.txt
https://github.com/prometheus/prometheus/releases/download/v1.7.1/sha256sums.txt
Writing updated prometheus manifest
```

thanks for the pointer @r15ch13

**Comment by r15ch13** [comment]
Thanks 👍

**Pull request merged**
