### PR TITLE
Fix license attributes to SPDX standard

### PR DESCRIPTION
**Pull request by rasa**
Final (?) attempt. I had to change errant `*-or-later`s to `*-only`s.

### CODE REVIEW

**Comment by rasa** [comment]
Once this is merged, I’ll submit https://github.com/rasa/scoop-extras/tree/rasa/fix-licenses-v2 and https://github.com/rasa/scoop-extras/tree/rasa/fix-licenses-m-z

**Comment by rasa** [comment]
I documented it [here](https://github.com/lukesampson/scoop/wiki/App-Manifests#optional-properties):
license: The software license for the program. For well-known licenses, please use the identifier found at https://spdx.org/licenses/ For other licenses, use the URL of the license, if available. Otherwise, use “Freeware”, “Proprietary”, “Public Domain”, or “Shareware”, as appropriate. If multiple licenses, seperate licenses with a comma (,). If dual licensed, seperate licenses with a pipe symbol (|).

We should update for the new schema.

**Comment by r15ch13** [comment]
Oh, okay. I missed that 😁

**Comment by h404bi** [comment]
So is it a backward compatibility update? What about user-defined buckets? And is there any tool/script can merge this change, for 3rd-party buckets?

**Comment by rasa** [comment]
It’s backwards compatible, so nothing will break. The `license` property can remain a string of any value.

**Comment by h404bi** [comment]
Ok, well done. It looks like the `scoop info` sub-command should also be enhanced to handle the new license property.

**Comment by rasa** [comment]
See #2380

**Pull request merged**
