### PR TITLE
Added fzf, exiftool, unar

### PR DESCRIPTION
**Pull request by Congee**

### CODE REVIEW

**Comment by r15ch13** [comment]
Nice, but could make the tests pass? You can install and run `pester` to run the tests. Also adding autoupdate information for fzf would be nice. https://github.com/lukesampson/scoop/wiki/App-Manifest-Autoupdate

**Comment by r15ch13** [comment]
One little thing missing. 😊 `checkver` needs to br added for getting new versions.

**Comment by Congee** [comment]
Thanks a lot for your help.

**Comment by Congee** [comment]
Pester is awesome in the first. But I got two errors that don't show in the Appveyor testing environment.
```
 [-] file newlines are CRLF 79ms
   ArgumentNullException: Value cannot be null.
   Parameter name: input
   MethodInvocationException: Exception calling "Split" with "2" argument(s): "Value cannot be null.
   Parameter name: input"
   at <ScriptBlock>, C:\Users\Congee\Projects\scoop\test\00-Project.Tests.ps1: line 138
```

```
   Context manifest validates against the schema
    [*] .#fzf.json: Error reading JObject from JsonReader. Path '', line 0, position 0.
    [-] .#fzf.json 93ms
      Expected: {0}
      But was:  {1}
      58:                 $validator.Errors.Count | should be 0
      at <ScriptBlock>, C:\Users\Congee\Projects\scoop\test\Scoop-Manifest.Tests.ps1: line 58
```
This costs me hours :/ . But I'm a unix guy. Really don't know how to debug the powershell test code.

**Comment by r15ch13** [comment]
Nice, but there is still one small thing 😉
The github checkver methods checks for the latest stable release. Fzf only buts those releases to the bin repo, so i think it would be better to use this for checkver. This would also mean downgrading to 0.16.5 for the time being.

I currently have no idea what to do with pester errors you. I will check them out later today 😊

**Comment by Congee** [comment]
Thanks for instructions!

**Comment by r15ch13** [comment]
No problem :)
But i still don't have an idea to solve your pester problems. try pulling the new files from git. maybe this fixes it :)

**Comment by Congee** [comment]
Pulled from upstream, still got these errors. It seems strange that first several pester checks didn't complain with these errors. Also, I tried removing the newsly added manifests files, pester still complains. So, this failure seems has nothing to do with this pull request. Better open a new ticket.

**Pull request merged**
