### PR TITLE
Use SPDX license identifiers in the default bucket

### PR DESCRIPTION
**Pull request by Calinou**
This leads to more consistent license properties and allows for easier automated parsing. I left the custom URLs in packages that use custom licenses or whose license isn't clearly defined.

See the [SPDX License List](https://spdx.org/licenses/) for more information.

### CODE REVIEW

**Comment by r15ch13** [comment]
Please remove the changes from test fixtures `broken_wget.json`, `invalid_wget.json` and `wget.json`.
These files don't need a correct license identifier.

**Comment by Calinou** [comment]
I updated the pull request, please check it again.

**Comment by rasa** [comment]
I updated the wiki with:

* `license`: The software license for the program. For well-known licenses, please use the identifier found at https://spdx.org/licenses/ For other licenses, use the URL of the license, if available. Otherwise, use “Freeware”, “Shareware”, or “Custom”, as appropriate.

Is that acceptable?

**Comment by Calinou** [comment]
@rasa Sounds good to me. :smiley:

**Pull request merged**
