### PR TITLE
less: sha256 hashes

### PR DESCRIPTION
**Pull request by martinlindhe**
Hello. Are these wanted? (md5 -> sha256 hashes)

If so, I can submit patches for the packages using md5 / sha1.

### CODE REVIEW

**Comment by lukesampson** [comment]
Usually if there are MD5 hashes used, it's because that's what the software developers publish. E.g. http://gnuwin32.sourceforge.net/packages/less.htm publishes Md5Sum next to the downloads so they're authoritative, as well as easier to put into the manifest.

**Comment by martinlindhe** [comment]
Okay, thanks for explaining.

The issue I would like to address by removing the md5 sums is hash collision. It is especially bad here because many of the buckets that come with md5 is served over http, thus allowing a man-in-the-middle attack on a untrusted network (the internet).
Md5 collision is quite cheap these days, and many of these older tools have had known md5 sums for years and years, so it would be safe to assume someone already produced collisions for them.

If you are unfamiliar with md5 collisions, see this page for some examples of win32 exes with different payload and same md5 hashes: http://www.mathstat.dal.ca/~selinger/md5collision/

Sha1 is also known to have collisions, but it requires much more processing power to produce collisions for these. Here is an example: https://eprint.iacr.org/2015/967

Sha256 is still a safe and good option to stick with.

**Comment by lukesampson** [comment]
You make a good case for sha256. I don't think we need to force everyone to use it, but if you're happy to submit patches then I'm good with that. Thanks.

**Comment by martinlindhe** [comment]
Okay, great! :smile:

**Pull request merged**
