### PR TITLE
Download functionality refactor

### PR DESCRIPTION
**Pull request by deevus**
The download output was always rudimentary and I have toyed with the idea of being able to replace the downloader with something like aria2c or axel. Initially I aimed at a general refactor but once I started going I couldn't help but make the download progress a bit nicer

### CODE REVIEW

**Comment by deevus** [comment]
animation

**Comment by deevus** [comment]
```
installing 7zip (16.04)
7z1604-x64.msi [======================================================================] (1.6 MB) 100%
done
checking hash...ok
extracting...done
linking ~\appdata\local\scoop\apps\7zip\current => ~\appdata\local\scoop\apps\7zip\16.04
creating shim for 7z
7zip (16.04) was installed successfully!
```

**Comment by deevus** [comment]
Multiple downloads

```
installing vim (8.0.069)
vim80-069w32.zip [======================================] (1.2 MB) 100%
done
checking hash...ok
extracting...done
vim80-069rt.zip [======================================] (10.3 MB) 100%
done
checking hash...ok
extracting...done
libiconv-1.9.1.bin.woe32.zip [========================] (680.9 KB) 100%
done
checking hash...ok
extracting...done
gettext-runtime-0.13.1.bin.woe32.zip [================] (163.7 KB) 100%
done
checking hash...ok
extracting...done
vimtutor.ps1 [==========================================] (1.0 KB) 100%
done
checking hash...ok
linking ~\appdata\local\scoop\apps\vim\current => ~\appdata\local\scoop\apps\vim\8.0.069
creating shim for vim
creating shim for vimtutor
running post-install script...
~/.vimrc exists, skipping
vim (8.0.069) was installed successfully!
```

**Comment by deevus** [comment]
I tried to record a GIF but it didn't turn out well

**Comment by deevus** [comment]
Possible next steps:

- Download all urls first, then check hashes, then extract
- Support another downloader like aria2c that can download multiple urls simultaneously and with multiple connections for improved speeds

**Comment by deevus** [comment]
@r15ch13 Awesome! What did you use to record the GIF? The program I'm using isn't working well since a recent update. 

One of those gifs could totally go on the homepage.

**Comment by r15ch13** [comment]
I used [ScreenToGif](http://www.screentogif.com/). That programm is awesome ❤️

**Pull request merged**
