### PR TITLE
Updated descriptions

### PR DESCRIPTION
**Pull request by gbursson**
updated descriptions of most applications from A to C.

### CODE REVIEW

**Comment by gbursson** [comment]
That's odd, seems like VSCode is auto-removing newline on save!

Will do it in Sublime maybe.

**Comment by Ash258** [comment]
Vscode setting: `"files.insertFinalNewline": true,`

**Comment by gbursson** [comment]
Thanks Ash :)

I fixed (I think) busybox and bfg manifests (oddly Sublime highlighted some parts of the "original" manifests as broken.

Can't fix composer.json issue, will leave it for now. Quick question, as I am just learning git - how to revert changes for one file only (i.e. composer manifest)?

**Comment by r15ch13** [comment]
@gbursson try [GitKraken](https://www.gitkraken.com/) it has an undo button.

**Pull request closed without merging**
