### PR TITLE
ldc: add ldc manifesto

### PR DESCRIPTION
**Pull request by kiridaruma**
from https://dlang.org/ ,
> D is a general-purpose programming language with static typing, systems-level access, and C-like syntax. With the D Programming Language, write fast, read fast, and run fast. 

ldc is LLVM based dlang compiler.

### CODE REVIEW

**Comment by r15ch13** [comment]
Please add `description` (`A LLVM based dlang compiler`) and `homepage` properties.

**Comment by kiridaruma** [comment]
I just added `description` and `homepage` properties.
anything else?

**Comment by h404bi** [comment]
Could you please add `license` field, too?

**Comment by kiridaruma** [comment]
I just add `license` field too.
anything else? or do you have app manifesto creator's guidelines? (should I read it?)
I read [this](https://github.com/lukesampson/scoop/wiki/App-Manifests).

**Comment by h404bi** [comment]
perfect, now waiting collaborators to merge.

**Pull request merged**
