### PR TITLE
Update dotnet-sdk to version 2.1.401

### PR DESCRIPTION
**Pull request by ggobbe**
It should also fix the auto update

### CODE REVIEW

**Comment by r15ch13** [comment]
Just found this `https://dotnetcli.blob.core.windows.net/dotnet/Sdk/2.1.401/` URL in https://github.com/dotnet/core/blob/master/release-notes/releases.csv
Appending `dotnet-sdk-2.1.401-win-x86.zip` works.

`https://dotnetcli.blob.core.windows.net/dotnet/Sdk/2.1.401/dotnet-sdk-2.1.401-win-x86.zip`
`https://dotnetcli.blob.core.windows.net/dotnet/Sdk/$version/dotnet-sdk-$version-win-x86.zip`

**Comment by r15ch13** [comment]
Some version check variants:
```json
"checkver": {
    "url": "https://raw.githubusercontent.com/dotnet/core/master/release-notes/releases.json"
    "re": "\"version-sdk\":\\s+\"(?<version>[\\d.]+)\","
}
```

```json
"checkver": {
    "url": "https://raw.githubusercontent.com/dotnet/core/master/release-notes/releases.csv"
    "re": "[\\d.]+,(?<version>[\\d.]+),"
}
```

**Comment by ggobbe** [comment]
The only issue with those links is that is it hard to filter betas, preview, rc releases from stable ones. There is a flag lts-runtime but it can be true even for a preview version if the runtime hasn't changed. 

Whereas on their home page, their main download link is always pointing to the latest stable version.

Let me know your thoughts. Thanks

**Comment by ggobbe** [comment]
@r15ch13 any update regarding this? The sdk is already two versions old and it would be nice to get the updates.

**Comment by r15ch13** [comment]
Betas, previews, release candidates all have some string in the version. Matching only digits and dots eliminates those versions. The SDK also has no LTS version, so this can also be ignored.

**Comment by ggobbe** [comment]
@r15ch13 I have applied your comments and updated the PR accordingly. Not sure about the auto-update because I sometimes see $matchVersion and sometimes $version.

**Comment by r15ch13** [comment]
`$version` is the right way to use it.
But `$matchVersion` is the same as `$version` :grin:

**Pull request merged**
