### PR TITLE
haskell: add 32bit

### PR DESCRIPTION
**Pull request by h404bi**
close #1676

### CODE REVIEW

**Comment by Ash258** [comment]
Hash extraction is possible from <https://www.haskell.org/platform/windows.html>

Something like `64 bit Core:<br><textarea.+>($sha256)`

**Comment by h404bi** [comment]
https://regex101.com/r/Nr6InZ/1/  you will get two matches.

**Comment by Ash258** [comment]
😒 They render windows first on windows end, but mac os hash is first in html ... 😒
Someone would expect, that `/windows.html` will contains only windows realease 🤷‍♂️

**Comment by Ash258** [comment]
Then this should do the trick:

32 bit is OK. And make 64 bit complex to specify boundaries between two windows specific text guards.

```json
"architecture": {
            "64bit": {
                "url": "https://haskell.org/platform/download/$version/HaskellPlatform-$version-core-x86_64-setup.exe",
                "hash": {
                    "url": "https://www.haskell.org/platform/windows.html",
                    "regex": "(?sm)Start Menu.*64 bit Core:<br><textarea.+>($sha256).*32 bit Core"
                }
            },
            "32bit": {
                "url": "https://haskell.org/platform/download/$version/HaskellPlatform-$version-core-i386-setup.exe",
                "hash": {
                    "url": "https://www.haskell.org/platform/windows.html",
                    "regex": "32 bit Core:<br><textarea.+>($sha256)"
                }
            }
        }
```

image

**Pull request merged**
