### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### lukesampson/scoop now has a Chat Room on Gitter

@deevus has just created a chat room. You can visit it here: [https://gitter.im/lukesampson/scoop](https://gitter.im/lukesampson/scoop?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/lukesampson/scoop?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by deevus** [comment]
@lukesampson How do you feel about using this?

**Comment by lukesampson** [comment]
I'm not sure I'd have time to participate.

**Comment by ntwb** [comment]
I'm so time poor these days, I doubt I'd have time to hang in a chat room either.

**Comment by lukesampson** [comment]
Sorry my earlier reply was a bit short. I think this could be a good idea @deevus, I just don't think I would personally be much use in a chat room.

My situation right now is that I need to focus on my day job during business hours, so I don't feel like I'd be able to participate much in a chat room. Email is good for me on Scoop because I can just ignore GitHub when I need to and then there's a queue of things to check when I get some spare time.

But maybe other people such as yourself can help out more in that way, and if you're happy to take that role I'm all for it.

Also @ntwb mentioned elsewhere that Slack might be a good tool too. To me, Gitter looks like it might be more useful as a way to provide quick help to people that are having trouble and need support, whereas I think GitHub tools are working pretty well for the team communication stuff that Slack provides.

**Comment by deevus** [comment]
I'd be happy to use Slack. I feel as if GitHub Issues isn't the best place for conversation so I'd really like somewhere to chat where everyone that wants to participate is included. 

For example If I have a question about the direction of Scoop I don't feel it's appropriate to discuss here.

**Comment by lukesampson** [comment]
OK cool, I've set up a Slack team for us—let me know if you didn't receive an invite. And is it worth having Gitter as well, do you think?

**Comment by deevus** [comment]
Just leave it for now. Slack should be enough.

**Pull request closed without merging**
