### PR TITLE
Fix broken Sourceforge URL

### PR DESCRIPTION
**Pull request by nilkesede**

### CODE REVIEW

**Comment by deevus** [comment]
The old address still works. Is there a reason we should migrate to this new one?

**Comment by lukesampson** [comment]
Yeah, merging this request would probably fix the problem for some people and break it for others.

Sourceforge mirrors are getting really flaky now, and they've disabled the download URLs that auto-redirect to the closest mirror.

We could look at writing a special case for SF urls to load the HTML and parse it to find the closest mirror , e.g. loading http://sourceforge.net/projects/sevenzip/files/7-Zip/9.20/7z920-x64.msi/download?nodownload=1 and looking for the `href` of the `<a class="direct-download">`.

**Comment by deevus** [comment]
Is there any reason we shouldn't use the main download links from http://www.7-zip.org/download.html to move away from Sourceforge?

**Comment by lukesampson** [comment]
I can't see any reason not to. They must have added those new links recently—nicely spotted.

**Comment by deevus** [comment]
@nilkesede Are you able to update and rebase your PR to use the main download links from http://www.7-zip.org/download.html ?

**Comment by deevus** [comment]
Fixed in e689df24dbfafc1f0137699c186fdf5b2332567a

**Pull request closed without merging**
